#ifndef RSSN_H
#define RSSN_H

/* Generated with cbindgen:0.29.4 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
/** The handle value that means "no term" (a failed constructor). */
#define RSSN_NO_TERM UINT32_MAX


#ifdef __cplusplus
namespace rssn {
#endif  // __cplusplus

/**
 * Outcome of an rssn C call.
 */
typedef enum RssnStatus {
    /**
     * Success.
     */
    RSSN_STATUS_OK = 0,
    /**
     * A required pointer argument was null.
     */
    RSSN_STATUS_NULL_ARGUMENT = 1,
    /**
     * A string argument was not valid UTF-8.
     */
    RSSN_STATUS_INVALID_UTF8 = 2,
    /**
     * Input text could not be parsed.
     */
    RSSN_STATUS_PARSE = 3,
    /**
     * An operator name is not registered, or got the wrong arity.
     */
    RSSN_STATUS_UNKNOWN_OPERATOR = 4,
    /**
     * A numeric answer was requested but none could be determined.
     */
    RSSN_STATUS_NOT_NUMERIC = 5,
    /**
     * A rule set derived a contradiction; discard the session.
     */
    RSSN_STATUS_INCONSISTENT = 6,
    /**
     * A rule set failed to install.
     */
    RSSN_STATUS_RULE = 7,
    /**
     * A term handle does not belong to the session.
     */
    RSSN_STATUS_NO_SUCH_TERM = 8,
    /**
     * The term has no value of the requested kind.
     */
    RSSN_STATUS_NO_VALUE = 9,
    /**
     * A simulation failed or was given bad parameters.
     */
    RSSN_STATUS_SIMULATION = 10,
    /**
     * rssn panicked; this is a bug.
     */
    RSSN_STATUS_PANIC = 11,
} RssnStatus;

/**
 * What to compute with and what to aim for. Opaque.
 */
typedef struct RssnConfig RssnConfig;

/**
 * An rssn session: owns every term made through it. Opaque.
 */
typedef struct RssnSession RssnSession;

/**
 * The result of `rssn_compute`.
 */
typedef struct RssnAnswer {
    /**
     * The answer term: a closed form, or a float literal for a numeric
     * target.
     */
    uint32_t term;
    /**
     * Whether `value` and `error` are meaningful.
     */
    bool has_value;
    /**
     * The numeric value, when known.
     */
    double value;
    /**
     * Estimated absolute error of `value`.
     */
    double error;
    /**
     * Whether the request was fully reduced; `false` means the term still
     * contains unevaluated operators.
     */
    bool reduced;
    /**
     * Outer iterations the engine performed.
     */
    size_t iterations;
} RssnAnswer;

/**
 * A dense numeric array extracted from a term, row-major.
 */
typedef struct RssnTensor {
    /**
     * Number of dimensions; 0 for a scalar.
     */
    size_t rank;
    /**
     * `rank` extents.
     */
    size_t *shape;
    /**
     * Number of entries (the product of the extents).
     */
    size_t len;
    /**
     * `len` values.
     */
    double *data;
} RssnTensor;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Reduces `term` to the target of `config` (null means the defaults) and
 * stores the result in `*out`.
 *
 * # Safety
 * `session` must be a live session, `config` null or a live
 * configuration, and `out` a valid pointer.
 */
enum RssnStatus rssn_compute(const struct RssnSession *session,
                             uint32_t term,
                             const struct RssnConfig *config,
                             struct RssnAnswer *out);

/**
 * Declares facts about the symbol `name`. `facts` is a bit set: 1 real,
 * 2 nonzero, 4 nonnegative, 8 nonpositive, 16 integer (so 7 is
 * "positive").
 *
 * # Safety
 * `config` must be a live configuration; `name` a NUL-terminated string.
 */
enum RssnStatus rssn_config_assume(struct RssnConfig *config, const char *name, uint8_t facts);

/**
 * Binds the symbol `name` to `value` for numeric evaluation.
 *
 * # Safety
 * `config` must be a live configuration; `name` a NUL-terminated string.
 */
enum RssnStatus rssn_config_bind(struct RssnConfig *config, const char *name, double value);

/**
 * Limits the search: at most `max_iterations` outer iterations and
 * `max_nodes` graph nodes. Zero keeps the current value.
 *
 * # Safety
 * `config` must be a live configuration.
 */
enum RssnStatus rssn_config_budget(struct RssnConfig *config,
                                   size_t max_iterations,
                                   size_t max_nodes);

/**
 * Releases a configuration. Null is ignored.
 *
 * # Safety
 * `config` must be null or come from `rssn_config_new`.
 */
void rssn_config_free(struct RssnConfig *config);

/**
 * A configuration with every standard rule set and a symbolic target.
 * Free it with `rssn_config_free`.
 */
struct RssnConfig *rssn_config_new(void);

/**
 * Asks for a numeric answer within the absolute `tolerance`.
 *
 * # Safety
 * `config` must be a live configuration.
 */
enum RssnStatus rssn_config_numeric(struct RssnConfig *config, double tolerance);

/**
 * Asks for a closed-form answer (the default).
 *
 * # Safety
 * `config` must be a live configuration.
 */
enum RssnStatus rssn_config_symbolic(struct RssnConfig *config);

/**
 * The message of the last failed call on this thread (empty if none).
 * The pointer stays valid until the next failing rssn call on this
 * thread; do not free it.
 */
const char *rssn_last_error(void);

/**
 * Releases a session and all its terms. Null is ignored.
 *
 * # Safety
 * `session` must be null or come from `rssn_session_new` and not be used
 * afterwards.
 */
void rssn_session_free(struct RssnSession *session);

/**
 * Creates a session with every standard rule set. Free it with
 * `rssn_session_free`. Returns null if the built-in rules fail to install.
 */
struct RssnSession *rssn_session_new(void);

/**
 * Runs the simulation scenario `name` (see
 * [`crate::sim::scenario::SCENARIOS`]) with JSON parameters and stores
 * the JSON result in `*out` (free with `rssn_string_free`).
 *
 * # Safety
 * `name` and `params` must be NUL-terminated strings; `out` must be a
 * valid pointer.
 */
enum RssnStatus rssn_sim_run(const char *name, const char *params, char **out);

/**
 * Shorthand: parses `source`, computes it with the defaults and returns
 * the answer term, or `RSSN_NO_TERM` (see `rssn_last_error`).
 *
 * # Safety
 * `session` must be a live session; `source` a NUL-terminated string.
 */
uint32_t rssn_simplify(const struct RssnSession *session, const char *source);

/**
 * Releases a string returned by rssn. Null is ignored.
 *
 * # Safety
 * `text` must be null or a string returned by rssn and not yet freed.
 */
void rssn_string_free(char *text);

/**
 * Releases the buffers of a tensor filled by `rssn_term_tensor_data` and
 * zeroes it. Null is ignored.
 *
 * # Safety
 * `tensor` must be null or filled by `rssn_term_tensor_data` and not yet
 * freed.
 */
void rssn_tensor_free(struct RssnTensor *tensor);

/**
 * Applies the operator named `op` to `count` argument handles.
 *
 * # Safety
 * `session` must be a live session, `op` a NUL-terminated string and
 * `args` point to `count` handles (it may be null when `count` is 0).
 */
uint32_t rssn_term_apply(const struct RssnSession *session,
                         const char *op,
                         const uint32_t *args,
                         size_t count);

/**
 * Evaluates a term numerically with `count` symbol bindings
 * `names[i] = values[i]`, without running any rules.
 *
 * # Safety
 * `session` must be a live session; `names` and `values` must hold
 * `count` entries (null when `count` is 0); `out` must be valid.
 */
enum RssnStatus rssn_term_eval(const struct RssnSession *session,
                               uint32_t term,
                               const char *const *names,
                               const double *values,
                               size_t count,
                               double *out);

/**
 * A floating point number.
 *
 * # Safety
 * `session` must be a live session.
 */
uint32_t rssn_term_float(const struct RssnSession *session, double value);

/**
 * An exact integer.
 *
 * # Safety
 * `session` must be a live session.
 */
uint32_t rssn_term_int(const struct RssnSession *session, int64_t value);

/**
 * Parses infix text such as `"diff(sin(x)^2, x)"`.
 *
 * # Safety
 * `session` must be a live session; `source` a NUL-terminated string.
 */
uint32_t rssn_term_parse(const struct RssnSession *session, const char *source);

/**
 * The exact fraction `numerator / denominator`, or `RSSN_NO_TERM` for a
 * zero denominator.
 *
 * # Safety
 * `session` must be a live session.
 */
uint32_t rssn_term_rational(const struct RssnSession *session,
                            int64_t numerator,
                            int64_t denominator);

/**
 * The symbol `name`, or `RSSN_NO_TERM`.
 *
 * # Safety
 * `session` must be a live session; `name` a NUL-terminated string.
 */
uint32_t rssn_term_sym(const struct RssnSession *session, const char *name);

/**
 * Extracts a (possibly nested) list of numbers as a dense array into
 * `*out`; release it with `rssn_tensor_free`.
 *
 * # Safety
 * `session` must be a live session and `out` a valid pointer.
 */
enum RssnStatus rssn_term_tensor_data(const struct RssnSession *session,
                                      uint32_t term,
                                      struct RssnTensor *out);

/**
 * Stores the value of a literal number term in `*out`.
 *
 * # Safety
 * `session` must be a live session and `out` a valid pointer.
 */
enum RssnStatus rssn_term_to_f64(const struct RssnSession *session, uint32_t term, double *out);

/**
 * The term as LaTeX math; free with `rssn_string_free`.
 *
 * # Safety
 * `session` must be a live session.
 */
char *rssn_term_to_latex(const struct RssnSession *session, uint32_t term);

/**
 * The term as a multi-line Unicode drawing; free with `rssn_string_free`.
 *
 * # Safety
 * `session` must be a live session.
 */
char *rssn_term_to_pretty(const struct RssnSession *session, uint32_t term);

/**
 * The term as infix text (parseable by `rssn_term_parse`); free with
 * `rssn_string_free`. Null on failure.
 *
 * # Safety
 * `session` must be a live session.
 */
char *rssn_term_to_string(const struct RssnSession *session, uint32_t term);

/**
 * The term as Typst math; free with `rssn_string_free`.
 *
 * # Safety
 * `session` must be a live session.
 */
char *rssn_term_to_typst(const struct RssnSession *session, uint32_t term);

/**
 * The crate version, e.g. `"0.3.0"`. Static; do not free.
 */
const char *rssn_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#ifdef __cplusplus
}  // namespace rssn
#endif  // __cplusplus

#endif  /* RSSN_H */
