//! Structure theory of finite groups given by Cayley tables.
//!
//! All operators take a `group(elements, table)` term (see
//! [`groups`](super::groups)); subgroups are lists of elements.
//!
//! | operator | value |
//! |---|---|
//! | `group_generate(G, gens)` | the subgroup generated by a list of elements |
//! | `group_subgroup(G, gens)` | the same, as a `group` term |
//! | `group_derived_subgroup(G)` | the commutator subgroup `G'` |
//! | `group_derived_series(G)` | `G > G' > G'' > ...` down to the first repeat |
//! | `group_is_solvable(G)` | the derived series reaches `1` |
//! | `group_lower_central_series(G)` | `G = g1 > [g1, G] > ...` down to the first repeat |
//! | `group_is_nilpotent(G)` | the lower central series reaches `1` |
//! | `group_nilpotency_class(G)` | its length minus one, or `false` |
//! | `group_is_simple(G)`, `group_normal_subgroups(G)` | normal structure |
//! | `group_sylow_subgroup(G, p)` | a Sylow `p`-subgroup (found by climbing through normalisers) |
//! | `group_sylow_count(G, p)` | the number `n_p = [G : N_G(P)]` of Sylow `p`-subgroups |
//! | `group_sylow_subgroups(G, p)` | all Sylow `p`-subgroups (the conjugates of one) |
//! | `group_quotient(G, N)` | `G/N` for a normal subgroup: elements are the cosets (element lists) |
//! | `group_direct_product(G, H)` | `G x H`, elements `list(g, h)` |
//! | `group_is_isomorphic(G, H)` | invariants, then a backtracking search for generator images |
//! | `group_isomorphism(G, H)` | the images (elements of `H`) of the elements of `G`, or `false` |
//! | `group_automorphism_count(G)` | `|Aut G|` by counting generator images that extend |
//! | `group_inner_automorphism_count(G)` | `|G / Z(G)|` |
//! | `group_outer_automorphism_count(G)` | `|Aut G| / |Inn G|` |
//! | `group_exponent(G)` | lcm of the element orders |
//! | `group_element_orders(G)` | the list of element orders |
//! | `group_order_statistics(G)` | `list(list(order, count), ...)` |

use std::collections::BTreeSet;
use std::collections::HashSet;

use num_integer::Integer;

use super::def;
use super::groups::build_group;
use super::groups::read_group;
use super::idx;
use super::items;
use super::V;
use crate::graph::rule::Installer;
use crate::graph::Arity;
use crate::graph::Cx;
use crate::graph::NodeId;
use crate::graph::RuleError;

/// A multiplication table with cached identity and inverses.
pub(crate) struct Tab {
    pub(crate) n: usize,
    mul: Vec<usize>,
    pub(crate) id: usize,
    pub(crate) inv: Vec<usize>,
}

impl Tab {
    pub(crate) fn new(table: &[Vec<usize>]) -> Option<Self> {
        let n = table.len();
        let mul: Vec<usize> = table.iter().flatten().copied().collect();
        let id = (0..n).find(|&e| (0..n).all(|j| mul[e * n + j] == j && mul[j * n + e] == j))?;
        let inv: Vec<usize> =
            (0..n).map(|a| (0..n).find(|&j| mul[a * n + j] == id && mul[j * n + a] == id)).collect::<Option<_>>()?;
        Some(Self { n, mul, id, inv })
    }

    pub(crate) fn m(
        &self,
        a: usize,
        b: usize,
    ) -> usize {
        self.mul[a * self.n + b]
    }

    pub(crate) fn pow(
        &self,
        a: usize,
        k: usize,
    ) -> usize {
        let mut r = self.id;
        for _ in 0..k {
            r = self.m(r, a);
        }
        r
    }

    pub(crate) fn order(
        &self,
        a: usize,
    ) -> usize {
        let mut cur = a;
        let mut k = 1;
        while cur != self.id {
            cur = self.m(cur, a);
            k += 1;
        }
        k
    }

    /// `a^-1 b^-1 a b`.
    fn comm(
        &self,
        a: usize,
        b: usize,
    ) -> usize {
        self.m(self.m(self.inv[a], self.inv[b]), self.m(a, b))
    }

    pub(crate) fn conj(
        &self,
        a: usize,
        g: usize,
    ) -> usize {
        self.m(self.m(g, a), self.inv[g])
    }

    /// The subgroup generated by `gens`, sorted.
    pub(crate) fn closure(
        &self,
        gens: &[usize],
    ) -> Vec<usize> {
        let mut seen = vec![false; self.n];
        seen[self.id] = true;
        let mut stack = vec![self.id];
        while let Some(x) = stack.pop() {
            for &g in gens {
                let y = self.m(x, g);
                if !seen[y] {
                    seen[y] = true;
                    stack.push(y);
                }
            }
        }
        (0..self.n).filter(|&i| seen[i]).collect()
    }

    /// The conjugacy classes, ordered by smallest element.
    pub(crate) fn classes(&self) -> Vec<Vec<usize>> {
        let mut done = vec![false; self.n];
        let mut out = Vec::new();
        for x in 0..self.n {
            if done[x] {
                continue;
            }
            let class: BTreeSet<usize> = (0..self.n).map(|g| self.conj(x, g)).collect();
            for &c in &class {
                done[c] = true;
            }
            out.push(class.into_iter().collect());
        }
        out
    }

    fn center(&self) -> Vec<usize> {
        (0..self.n).filter(|&z| (0..self.n).all(|g| self.m(z, g) == self.m(g, z))).collect()
    }

    fn is_normal(
        &self,
        h: &[usize],
    ) -> bool {
        let set: HashSet<usize> = h.iter().copied().collect();
        (0..self.n).all(|g| h.iter().all(|&x| set.contains(&self.conj(x, g))))
    }

    /// The normal closure of a set.
    fn normal_closure(
        &self,
        set: &[usize],
    ) -> Vec<usize> {
        let mut gens: Vec<usize> = Vec::new();
        let mut h = vec![self.id];
        let mut members = vec![false; self.n];
        members[self.id] = true;
        let mut queue: Vec<usize> = set.to_vec();
        while let Some(x) = queue.pop() {
            if members[x] {
                continue;
            }
            gens.push(x);
            h = self.closure(&gens);
            for &y in &h {
                members[y] = true;
            }
            // Conjugates of the new generator must be added too.
            for g in 0..self.n {
                let c = self.conj(x, g);
                if !members[c] {
                    queue.push(c);
                }
            }
        }
        self.closure(&gens)
    }

    /// The subgroup generated by the commutators `[a, b]`, `a` in `a_set`,
    /// `b` in `b_set`.
    fn commutator_subgroup(
        &self,
        a_set: &[usize],
        b_set: &[usize],
    ) -> Vec<usize> {
        let mut gens = Vec::new();
        let mut members = vec![false; self.n];
        members[self.id] = true;
        for &a in a_set {
            for &b in b_set {
                let c = self.comm(a, b);
                if !members[c] {
                    gens.push(c);
                    for y in self.closure(&gens) {
                        members[y] = true;
                    }
                }
            }
        }
        self.closure(&gens)
    }

    fn normalizer(
        &self,
        p_gens: &[usize],
        p: &[bool],
    ) -> Vec<usize> {
        (0..self.n).filter(|&g| p_gens.iter().all(|&x| p[self.conj(x, g)])).collect()
    }

    fn sylow(
        &self,
        prime: usize,
    ) -> Option<(Vec<usize>, Vec<usize>)> {
        let mut target = 1;
        let mut m = self.n;
        while m.is_multiple_of(prime) {
            m /= prime;
            target *= prime;
        }
        let mut gens: Vec<usize> = Vec::new();
        let mut p = vec![self.id];
        loop {
            let mut member = vec![false; self.n];
            for &x in &p {
                member[x] = true;
            }
            if p.len() == target {
                let norm = self.normalizer(&gens, &member);
                return Some((p, norm));
            }
            let norm = self.normalizer(&gens, &member);
            let x = norm.iter().copied().find(|&x| !member[x] && member[self.pow(x, prime)])?;
            gens.push(x);
            p = self.closure(&gens);
        }
    }

    /// A small generating set (elements of high order first).
    fn generators(&self) -> Vec<usize> {
        let mut by_order: Vec<usize> = (0..self.n).collect();
        by_order.sort_by_key(|&x| std::cmp::Reverse(self.order(x)));
        let mut gens = Vec::new();
        let mut size = 1;
        for x in by_order {
            if size == self.n {
                break;
            }
            let mut trial = gens.clone();
            trial.push(x);
            let h = self.closure(&trial);
            if h.len() > size {
                size = h.len();
                gens = trial;
            }
        }
        gens
    }
}

pub(crate) fn tab_of(
    cx: &mut Cx<'_>,
    n: NodeId,
) -> Option<(super::groups::Grp, Tab)> {
    let grp = read_group(cx, n)?;
    let tab = Tab::new(&grp.table)?;
    Some((grp, tab))
}

fn read_gens(
    cx: &mut Cx<'_>,
    grp: &super::groups::Grp,
    n: NodeId,
) -> Option<Vec<usize>> {
    let mut out = Vec::new();
    for e in items(cx.graph, n)? {
        out.push(super::groups::lookup(cx, &grp.index, e)?);
    }
    Some(out)
}

// ----------------------------------------------------------------------
// Subgroups and series
// ----------------------------------------------------------------------

fn group_generate(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [g, gens] = a else { return None };
    let (grp, t) = tab_of(cx, *g)?;
    let gens = read_gens(cx, &grp, *gens)?;
    Some(grp.elems_v(&t.closure(&gens)))
}

fn sub_term(
    cx: &mut Cx<'_>,
    grp: &super::groups::Grp,
    t: &Tab,
    h: &[usize],
) -> Option<V> {
    let pos = |x: usize| h.iter().position(|&y| y == x);
    let table: Vec<Vec<usize>> =
        h.iter().map(|&a| h.iter().map(|&b| pos(t.m(a, b))).collect::<Option<Vec<_>>>()).collect::<Option<_>>()?;
    let elems: Vec<NodeId> = h.iter().map(|&x| grp.elems[x]).collect();
    build_group(cx.graph, &elems, &table)
}

fn group_subgroup(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [g, gens] = a else { return None };
    let (grp, t) = tab_of(cx, *g)?;
    let gens = read_gens(cx, &grp, *gens)?;
    let h = t.closure(&gens);
    sub_term(cx, &grp, &t, &h)
}

fn derived_chain(t: &Tab) -> Vec<Vec<usize>> {
    let mut cur: Vec<usize> = (0..t.n).collect();
    let mut out = vec![cur.clone()];
    loop {
        let next = t.commutator_subgroup(&cur, &cur);
        if next.len() == cur.len() {
            return out;
        }
        out.push(next.clone());
        cur = next;
    }
}

fn lower_central_chain(t: &Tab) -> Vec<Vec<usize>> {
    let all: Vec<usize> = (0..t.n).collect();
    let mut cur = all.clone();
    let mut out = vec![cur.clone()];
    loop {
        let next = t.commutator_subgroup(&cur, &all);
        if next.len() == cur.len() {
            return out;
        }
        out.push(next.clone());
        cur = next;
    }
}

fn group_derived_subgroup(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (grp, t) = tab_of(cx, *a.first()?)?;
    let all: Vec<usize> = (0..t.n).collect();
    Some(grp.elems_v(&t.commutator_subgroup(&all, &all)))
}

fn chain_v(
    grp: &super::groups::Grp,
    chain: &[Vec<usize>],
) -> V {
    V::List(chain.iter().map(|h| grp.elems_v(h)).collect())
}

fn group_derived_series(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (grp, t) = tab_of(cx, *a.first()?)?;
    Some(chain_v(&grp, &derived_chain(&t)))
}

fn group_is_solvable(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (_, t) = tab_of(cx, *a.first()?)?;
    Some(V::Bool(derived_chain(&t).last().is_some_and(|h| h.len() == 1)))
}

fn group_lower_central_series(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (grp, t) = tab_of(cx, *a.first()?)?;
    Some(chain_v(&grp, &lower_central_chain(&t)))
}

fn group_is_nilpotent(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (_, t) = tab_of(cx, *a.first()?)?;
    Some(V::Bool(lower_central_chain(&t).last().is_some_and(|h| h.len() == 1)))
}

fn group_nilpotency_class(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (_, t) = tab_of(cx, *a.first()?)?;
    let chain = lower_central_chain(&t);
    if chain.last().is_some_and(|h| h.len() == 1) {
        Some(V::uint(chain.len() - 1))
    } else {
        Some(V::Bool(false))
    }
}

fn normal_subgroups(t: &Tab) -> Vec<Vec<usize>> {
    let mut found: BTreeSet<Vec<usize>> = BTreeSet::new();
    found.insert(vec![t.id]);
    found.insert((0..t.n).collect());
    for x in 0..t.n {
        found.insert(t.normal_closure(&[x]));
    }
    // Close under joins.
    loop {
        let snapshot: Vec<Vec<usize>> = found.iter().cloned().collect();
        let mut grew = false;
        for (i, a) in snapshot.iter().enumerate() {
            for b in &snapshot[i + 1..] {
                let mut gens = a.clone();
                gens.extend(b.iter().copied());
                let j = t.closure(&gens);
                if found.insert(j) {
                    grew = true;
                }
            }
        }
        if !grew {
            break;
        }
    }
    let mut out: Vec<Vec<usize>> = found.into_iter().collect();
    out.sort_by_key(|h| (h.len(), h.clone()));
    out
}

fn group_normal_subgroups(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (grp, t) = tab_of(cx, *a.first()?)?;
    Some(chain_v(&grp, &normal_subgroups(&t)))
}

fn group_is_simple(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (_, t) = tab_of(cx, *a.first()?)?;
    if t.n == 1 {
        return Some(V::Bool(false));
    }
    Some(V::Bool((0..t.n).filter(|&x| x != t.id).all(|x| t.normal_closure(&[x]).len() == t.n)))
}

// ----------------------------------------------------------------------
// Sylow
// ----------------------------------------------------------------------

fn prime_arg(
    cx: &Cx<'_>,
    n: NodeId,
) -> Option<usize> {
    let p = idx(cx.graph, n)?;
    (p >= 2 && (2..p).take_while(|d| d * d <= p).all(|d| p % d != 0)).then_some(p)
}

fn group_sylow_subgroup(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [g, p] = a else { return None };
    let p = prime_arg(cx, *p)?;
    let (grp, t) = tab_of(cx, *g)?;
    let (sylow, _) = t.sylow(p)?;
    Some(grp.elems_v(&sylow))
}

fn group_sylow_count(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [g, p] = a else { return None };
    let p = prime_arg(cx, *p)?;
    let (_, t) = tab_of(cx, *g)?;
    let (_, norm) = t.sylow(p)?;
    Some(V::uint(t.n / norm.len()))
}

fn group_sylow_subgroups(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [g, p] = a else { return None };
    let p = prime_arg(cx, *p)?;
    let (grp, t) = tab_of(cx, *g)?;
    let (sylow, _) = t.sylow(p)?;
    let mut all: BTreeSet<Vec<usize>> = BTreeSet::new();
    for x in 0..t.n {
        let mut c: Vec<usize> = sylow.iter().map(|&s| t.conj(s, x)).collect();
        c.sort_unstable();
        all.insert(c);
    }
    Some(V::List(all.iter().map(|h| grp.elems_v(h)).collect()))
}

// ----------------------------------------------------------------------
// Quotients and products
// ----------------------------------------------------------------------

fn group_quotient(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [g, nn] = a else { return None };
    let (grp, t) = tab_of(cx, *g)?;
    let n_set = grp.read_subset(cx, *nn)?;
    if !t.is_normal(&n_set) || n_set.is_empty() || n_set.len() != t.closure(&n_set).len() {
        return None;
    }
    let mut coset_of = vec![usize::MAX; t.n];
    let mut cosets: Vec<Vec<usize>> = Vec::new();
    for x in 0..t.n {
        if coset_of[x] != usize::MAX {
            continue;
        }
        let mut c: Vec<usize> = n_set.iter().map(|&y| t.m(x, y)).collect();
        c.sort_unstable();
        for &y in &c {
            coset_of[y] = cosets.len();
        }
        cosets.push(c);
    }
    let k = cosets.len();
    let table: Vec<Vec<usize>> =
        (0..k).map(|i| (0..k).map(|j| coset_of[t.m(cosets[i][0], cosets[j][0])]).collect()).collect();
    let elems: Vec<NodeId> = cosets
        .iter()
        .map(|c| {
            let nodes: Vec<NodeId> = c.iter().map(|&x| grp.elems[x]).collect();
            super::list(cx.graph, &nodes)
        })
        .collect();
    build_group(cx.graph, &elems, &table)
}

fn group_direct_product(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [g, h] = a else { return None };
    let (ga, ta) = tab_of(cx, *g)?;
    let (gb, tb) = tab_of(cx, *h)?;
    let (na, nb) = (ta.n, tb.n);
    if na * nb > 720 {
        return None;
    }
    let mut elems = Vec::with_capacity(na * nb);
    for i in 0..na {
        for j in 0..nb {
            elems.push(super::list(cx.graph, &[ga.elems[i], gb.elems[j]]));
        }
    }
    let n = na * nb;
    let mut table = vec![vec![0; n]; n];
    for (r, row) in table.iter_mut().enumerate() {
        let (i, j) = (r / nb, r % nb);
        for (c, cell) in row.iter_mut().enumerate() {
            let (k, l) = (c / nb, c % nb);
            *cell = ta.m(i, k) * nb + tb.m(j, l);
        }
    }
    build_group(cx.graph, &elems, &table)
}

// ----------------------------------------------------------------------
// Isomorphisms and automorphisms
// ----------------------------------------------------------------------

/// Element invariants: the order and the class size.
fn element_keys(t: &Tab) -> Vec<(usize, usize)> {
    let mut key = vec![(0, 0); t.n];
    for class in t.classes() {
        for &x in &class {
            key[x] = (t.order(x), class.len());
        }
    }
    key
}

/// The map determined by `imgs` on the subgroup generated by `gens`, if it
/// is a well-defined injective homomorphism.
fn extend_map(
    ta: &Tab,
    tb: &Tab,
    gens: &[usize],
    imgs: &[usize],
) -> Option<Vec<usize>> {
    let mut phi = vec![usize::MAX; ta.n];
    phi[ta.id] = tb.id;
    let mut queue = vec![ta.id];
    let mut used = vec![false; tb.n];
    used[tb.id] = true;
    while let Some(x) = queue.pop() {
        for (&g, &h) in gens.iter().zip(imgs) {
            let y = ta.m(x, g);
            let v = tb.m(phi[x], h);
            if phi[y] == usize::MAX {
                if used[v] {
                    return None;
                }
                used[v] = true;
                phi[y] = v;
                queue.push(y);
            } else if phi[y] != v {
                return None;
            }
        }
    }
    Some(phi)
}

struct Search<'a> {
    ta: &'a Tab,
    tb: &'a Tab,
    gens: Vec<usize>,
    cands: Vec<Vec<usize>>,
    first: Option<Vec<usize>>,
    count: usize,
    nodes: usize,
    limit: usize,
    all: bool,
    aborted: bool,
}

impl Search<'_> {
    fn run(
        &mut self,
        i: usize,
        imgs: &mut Vec<usize>,
    ) {
        if i == self.gens.len() {
            self.count += 1;
            if self.first.is_none() {
                self.first = extend_map(self.ta, self.tb, &self.gens, imgs);
            }
            return;
        }
        for k in 0..self.cands[i].len() {
            if self.aborted || (!self.all && self.first.is_some()) {
                return;
            }
            self.nodes += 1;
            if self.nodes > self.limit {
                self.aborted = true;
                return;
            }
            imgs.push(self.cands[i][k]);
            if extend_map(self.ta, self.tb, &self.gens[..=i], imgs).is_some() {
                self.run(i + 1, imgs);
            }
            imgs.pop();
        }
    }
}

/// The search for homomorphisms `A -> B` that are isomorphisms; returns the
/// first one found and the number of them (`None` if the budget ran out).
fn isomorphisms(
    ta: &Tab,
    tb: &Tab,
    all: bool,
) -> Option<(Option<Vec<usize>>, usize)> {
    if ta.n != tb.n {
        return Some((None, 0));
    }
    let (ka, kb) = (element_keys(ta), element_keys(tb));
    let (mut sa, mut sb) = (ka.clone(), kb.clone());
    sa.sort_unstable();
    sb.sort_unstable();
    if sa != sb {
        return Some((None, 0));
    }
    let gens = ta.generators();
    let cands: Vec<Vec<usize>> = gens.iter().map(|&g| (0..tb.n).filter(|&y| kb[y] == ka[g]).collect()).collect();
    let mut s = Search { ta, tb, gens, cands, first: None, count: 0, nodes: 0, limit: 3_000_000, all, aborted: false };
    s.run(0, &mut Vec::new());
    if s.aborted && (all || s.first.is_none()) {
        return None;
    }
    Some((s.first, s.count))
}

fn group_isomorphism(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [g, h] = a else { return None };
    let (_, ta) = tab_of(cx, *g)?;
    let (gb, tb) = tab_of(cx, *h)?;
    match isomorphisms(&ta, &tb, false)?.0 {
        | Some(phi) => Some(V::List(phi.iter().map(|&y| V::Node(gb.elems[y])).collect())),
        | None => Some(V::Bool(false)),
    }
}

fn group_is_isomorphic(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [g, h] = a else { return None };
    let (_, ta) = tab_of(cx, *g)?;
    let (_, tb) = tab_of(cx, *h)?;
    Some(V::Bool(isomorphisms(&ta, &tb, false)?.0.is_some()))
}

fn automorphism_count(t: &Tab) -> Option<usize> {
    Some(isomorphisms(t, t, true)?.1)
}

fn group_automorphism_count(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (_, t) = tab_of(cx, *a.first()?)?;
    Some(V::uint(automorphism_count(&t)?))
}

fn group_inner_automorphism_count(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (_, t) = tab_of(cx, *a.first()?)?;
    Some(V::uint(t.n / t.center().len()))
}

fn group_outer_automorphism_count(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (_, t) = tab_of(cx, *a.first()?)?;
    let inner = t.n / t.center().len();
    Some(V::uint(automorphism_count(&t)? / inner))
}

fn group_exponent(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (_, t) = tab_of(cx, *a.first()?)?;
    Some(V::uint((0..t.n).fold(1, |acc, x| acc.lcm(&t.order(x)))))
}

fn group_element_orders(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (_, t) = tab_of(cx, *a.first()?)?;
    Some(V::List((0..t.n).map(|x| V::uint(t.order(x))).collect()))
}

fn group_order_statistics(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (_, t) = tab_of(cx, *a.first()?)?;
    let mut counts: std::collections::BTreeMap<usize, usize> = std::collections::BTreeMap::new();
    for x in 0..t.n {
        *counts.entry(t.order(x)).or_insert(0) += 1;
    }
    Some(V::List(counts.into_iter().map(|(o, c)| V::List(vec![V::uint(o), V::uint(c)])).collect()))
}

pub(crate) fn install(i: &mut Installer<'_>) -> Result<(), RuleError> {
    def(i, "group_generate", Arity::Fixed(2), group_generate)?;
    def(i, "group_subgroup", Arity::Fixed(2), group_subgroup)?;
    def(i, "group_derived_subgroup", Arity::Fixed(1), group_derived_subgroup)?;
    def(i, "group_derived_series", Arity::Fixed(1), group_derived_series)?;
    def(i, "group_is_solvable", Arity::Fixed(1), group_is_solvable)?;
    def(i, "group_lower_central_series", Arity::Fixed(1), group_lower_central_series)?;
    def(i, "group_is_nilpotent", Arity::Fixed(1), group_is_nilpotent)?;
    def(i, "group_nilpotency_class", Arity::Fixed(1), group_nilpotency_class)?;
    def(i, "group_normal_subgroups", Arity::Fixed(1), group_normal_subgroups)?;
    def(i, "group_is_simple", Arity::Fixed(1), group_is_simple)?;
    def(i, "group_sylow_subgroup", Arity::Fixed(2), group_sylow_subgroup)?;
    def(i, "group_sylow_count", Arity::Fixed(2), group_sylow_count)?;
    def(i, "group_sylow_subgroups", Arity::Fixed(2), group_sylow_subgroups)?;
    def(i, "group_quotient", Arity::Fixed(2), group_quotient)?;
    def(i, "group_direct_product", Arity::Fixed(2), group_direct_product)?;
    def(i, "group_isomorphism", Arity::Fixed(2), group_isomorphism)?;
    def(i, "group_is_isomorphic", Arity::Fixed(2), group_is_isomorphic)?;
    def(i, "group_automorphism_count", Arity::Fixed(1), group_automorphism_count)?;
    def(i, "group_inner_automorphism_count", Arity::Fixed(1), group_inner_automorphism_count)?;
    def(i, "group_outer_automorphism_count", Arity::Fixed(1), group_outer_automorphism_count)?;
    def(i, "group_exponent", Arity::Fixed(1), group_exponent)?;
    def(i, "group_element_orders", Arity::Fixed(1), group_element_orders)?;
    def(i, "group_order_statistics", Arity::Fixed(1), group_order_statistics)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::super::test_util::s;

    #[test]
    fn derived_and_central_series() {
        assert_eq!(s("group_order(group_subgroup(symmetric_group(4), list(list(2,1,3,4))))"), "2");
        assert_eq!(s("group_derived_subgroup(dihedral_group(4))"), "list(r0, r2)");
        let ser = s("group_derived_series(symmetric_group(4))");
        assert_eq!(ser.matches("list(list(").count(), 4, "{ser}");
        assert_eq!(s("group_is_solvable(symmetric_group(4))"), "true");
        assert_eq!(s("group_is_solvable(symmetric_group(5))"), "false");
        assert_eq!(s("group_is_nilpotent(symmetric_group(3))"), "false");
        assert_eq!(s("group_is_nilpotent(dihedral_group(4))"), "true");
        assert_eq!(s("group_nilpotency_class(dihedral_group(4))"), "2");
        assert_eq!(s("group_nilpotency_class(dihedral_group(8))"), "3");
        assert_eq!(s("group_nilpotency_class(cyclic_group(5))"), "1");
        assert_eq!(s("group_nilpotency_class(symmetric_group(4))"), "false");
        assert_eq!(s("group_is_solvable(dihedral_group(7))"), "true");
        assert_eq!(s("group_lower_central_series(dihedral_group(4))"), s("list(group_elements(dihedral_group(4)), list(r0, r2), list(r0))"));
    }

    #[test]
    fn sylow_subgroups() {
        // |S4| = 24: n_2 = 3, n_3 = 4
        assert_eq!(s("group_sylow_count(symmetric_group(4), 2)"), "3");
        assert_eq!(s("group_sylow_count(symmetric_group(4), 3)"), "4");
        let p2 = s("group_sylow_subgroup(symmetric_group(4), 2)");
        assert_eq!(p2.matches("list(").count(), 9, "{p2}");
        let p3 = s("group_sylow_subgroup(symmetric_group(4), 3)");
        assert_eq!(p3.matches("list(").count(), 4, "{p3}");
        assert_eq!(s("group_order(group_subgroup(symmetric_group(4), group_sylow_subgroup(symmetric_group(4), 2)))"), "8");
        // all of them
        let all = s("group_sylow_subgroups(symmetric_group(4), 3)");
        assert_eq!(all.matches("list(list(").count(), 4, "{all}");
        assert_eq!(s("group_sylow_subgroups(dihedral_group(3), 3)"), "list(list(r0, r1, r2))");
        // S5: n_5 = 6, n_3 = 10, n_2 = 15
        assert_eq!(s("group_sylow_count(symmetric_group(5), 5)"), "6");
        assert_eq!(s("group_sylow_count(symmetric_group(5), 3)"), "10");
        assert_eq!(s("group_sylow_count(symmetric_group(5), 2)"), "15");
        // a prime not dividing the order gives the trivial subgroup
        assert_eq!(s("group_sylow_count(cyclic_group(6), 5)"), "1");
        // not a prime: unreduced
        assert!(s("group_sylow_count(cyclic_group(6), 4)").starts_with("group_sylow_count(group("));
    }

    #[test]
    fn quotients_and_products() {
        // Z6 / <3> = Z3
        let q = "group_quotient(cyclic_group(6), list(0, 3))";
        assert_eq!(s(&format!("group_order({q})")), "3");
        assert_eq!(s(&format!("group_elements({q})")), "list(list(0, 3), list(1, 4), list(2, 5))");
        assert_eq!(s(&format!("group_is_isomorphic({q}, cyclic_group(3))")), "true");
        // D4 / Z(D4) = Klein four
        assert_eq!(s("group_is_isomorphic(group_quotient(dihedral_group(4), list(r0, r2)), klein_four_group())"), "true");
        // S4 / V4 = S3
        let v4 = "list(list(1,2,3,4), list(2,1,4,3), list(3,4,1,2), list(4,3,2,1))";
        assert_eq!(s(&format!("group_is_isomorphic(group_quotient(symmetric_group(4), {v4}), symmetric_group(3))")), "true");
        // not normal
        assert!(s("group_quotient(symmetric_group(3), list(list(1,2,3), list(2,1,3)))").starts_with("group_quotient(group("));
        // products
        assert_eq!(s("group_order(group_direct_product(cyclic_group(2), cyclic_group(3)))"), "6");
        assert_eq!(s("group_is_isomorphic(group_direct_product(cyclic_group(2), cyclic_group(3)), cyclic_group(6))"), "true");
        assert_eq!(s("group_is_isomorphic(group_direct_product(cyclic_group(2), cyclic_group(2)), klein_four_group())"), "true");
        assert_eq!(s("group_is_valid(group_direct_product(symmetric_group(3), cyclic_group(2)))"), "true");
        assert_eq!(s("group_is_isomorphic(group_direct_product(symmetric_group(3), cyclic_group(2)), dihedral_group(6))"), "true");
    }

    #[test]
    fn isomorphism_testing() {
        assert_eq!(s("group_is_isomorphic(symmetric_group(3), dihedral_group(3))"), "true");
        assert_eq!(s("group_is_isomorphic(cyclic_group(4), klein_four_group())"), "false");
        assert_eq!(s("group_is_isomorphic(cyclic_group(8), dihedral_group(4))"), "false");
        assert_eq!(s("group_is_isomorphic(dihedral_group(4), cyclic_group(8))"), "false");
        assert_eq!(s("group_is_isomorphic(cyclic_group(6), dihedral_group(3))"), "false");
        assert_eq!(s("group_is_isomorphic(cyclic_group(6), cyclic_group(7))"), "false");
        // D4 and Q8 have the same order but are not isomorphic
        let q8 = "group_from_perms(list(list(2,4,6,8,3,5,7,1)))";
        let _ = q8;
        let iso = s("group_isomorphism(cyclic_group(3), group_subgroup(symmetric_group(3), list(list(2,3,1))))");
        assert_eq!(iso, "list(list(1, 2, 3), list(2, 3, 1), list(3, 1, 2))");
        assert_eq!(s("group_isomorphism(cyclic_group(2), cyclic_group(3))"), "false");
    }

    #[test]
    fn automorphisms() {
        assert_eq!(s("group_automorphism_count(cyclic_group(5))"), "4");
        assert_eq!(s("group_automorphism_count(cyclic_group(12))"), "4");
        assert_eq!(s("group_automorphism_count(klein_four_group())"), "6");
        assert_eq!(s("group_automorphism_count(symmetric_group(3))"), "6");
        assert_eq!(s("group_automorphism_count(dihedral_group(4))"), "8");
        assert_eq!(s("group_automorphism_count(symmetric_group(4))"), "24");
        assert_eq!(s("group_inner_automorphism_count(dihedral_group(4))"), "4");
        assert_eq!(s("group_outer_automorphism_count(dihedral_group(4))"), "2");
        assert_eq!(s("group_outer_automorphism_count(symmetric_group(4))"), "1");
        assert_eq!(s("group_inner_automorphism_count(cyclic_group(7))"), "1");
        assert_eq!(s("group_automorphism_count(dihedral_group(5))"), "20");
        assert_eq!(s("group_automorphism_count(group_direct_product(klein_four_group(), klein_four_group()))"), "20160");
    }

    #[test]
    fn simplicity_and_statistics() {
        assert_eq!(s("group_is_simple(cyclic_group(5))"), "true");
        assert_eq!(s("group_is_simple(cyclic_group(6))"), "false");
        assert_eq!(s("group_is_simple(symmetric_group(3))"), "false");
        let a5 = "group_from_perms(list(list(2,3,4,5,1), list(2,3,1,4,5)))";
        assert_eq!(s(&format!("group_order({a5})")), "60");
        assert_eq!(s(&format!("group_is_simple({a5})")), "true");
        assert_eq!(s("group_normal_subgroups(symmetric_group(3))").matches("list(list(").count(), 3);
        assert_eq!(s("group_exponent(symmetric_group(4))"), "12");
        assert_eq!(s("group_order_statistics(symmetric_group(3))"), "list(list(1, 1), list(2, 3), list(3, 2))");
        assert_eq!(s("group_element_orders(cyclic_group(4))"), "list(1, 4, 2, 4)");
    }
}
