//! Permutation groups: Schreier–Sims, Todd–Coxeter and derived structure.
//!
//! A permutation of `n` points is the list of the images of `1, ..., n`
//! (see [`groups`](super::groups)); a permutation group is given by a list
//! of generators of equal degree. The product is `(p q)(i) = p(q(i))`.
//!
//! The group is represented by a *stabiliser chain* (a base and a strong
//! generating set) computed by the deterministic Schreier–Sims algorithm, so
//! order, membership and orbit–stabiliser data are exact for groups of any
//! order that fits the degree (the order is an arbitrary-precision integer).
//!
//! | operator | value |
//! |---|---|
//! | `perm_group_order(gens)` | the order, by Schreier–Sims |
//! | `perm_group_contains(gens, p)` | membership test (sifting) |
//! | `perm_group_base(gens)` | a base: points whose pointwise stabiliser is trivial |
//! | `perm_group_strong_generators(gens)` | a strong generating set relative to the base |
//! | `perm_group_basic_orbits(gens)` | the lengths of the basic orbits (their product is the order) |
//! | `perm_group_orbits(gens)` | the orbits on the points |
//! | `perm_group_is_transitive(gens)` | one orbit |
//! | `perm_group_stabilizer_order(gens, i)` | order of the stabiliser of point `i` |
//! | `perm_group_elements(gens)` | all elements (order at most 5040) |
//! | `group_from_perms(gens)` | the `group(elements, table)` term (order at most 720) |
//! | `perm_group_is_abelian(gens)` | commutativity |
//! | `perm_group_derived_series(gens)` | orders of the derived series `G = G0 > G1 > ...` (stops at the perfect core) |
//! | `perm_group_is_solvable(gens)` | the derived series reaches the trivial group |
//! | `perm_group_lower_central_series(gens)` | orders of `G = g1 > g2 > ...` with `g(i+1) = [gi, G]` |
//! | `perm_group_is_nilpotent(gens)` | the lower central series reaches the trivial group |
//! | `perm_group_derived_subgroup(gens)` | generators of `G'` |
//! | `todd_coxeter(gens, relators, subgroup_gens)` | `list(index, list(perm per generator))`: the coset enumeration of `<gens | relators>` over the subgroup, by the HLT strategy with coincidences |
//! | `todd_coxeter_index(gens, relators, subgroup_gens)` | only the index |
//! | `fp_group_order(gens, relators)` | the order of a presented group (index of the trivial subgroup) |
//! | `fp_group(gens, relators)` | the presented group as a `group` term (order at most 720) |
//!
//! Presentations: `gens` is a list of generator symbols; a word is a list of
//! letters, each a generator `a`, a power `a^k` (negative for the inverse),
//! or a non-zero integer `+-i` for the `i`-th generator or its inverse. The
//! relators are words; `list(a, a, a)`, `list(a^3)` and `list(1, 1, 1)` all
//! stand for `a^3`.

// Index loops over several parallel tables and float comparisons with explicit
// tolerances read better than the iterator forms; `as` casts convert small,
// non-negative, bounded values.
#![allow(
    clippy::needless_range_loop,
    clippy::float_cmp,
    clippy::cast_sign_loss,
    clippy::manual_midpoint
)]

use std::collections::HashMap;
use std::collections::HashSet;

use num_bigint::BigInt;

use super::def;
use super::groups::build_group;
use super::idx;
use super::items;
use super::V;
use crate::graph::op::core;
use crate::graph::rule::Installer;
use crate::graph::Arity;
use crate::graph::Cx;
use crate::graph::Graph;
use crate::graph::NodeId;
use crate::graph::RuleError;

/// A permutation as 0-based images.
pub(crate) type Perm = Vec<usize>;

/// The largest order for which all elements are listed.
const ELEMENT_LIMIT: usize = 5040;
/// The largest order for which a table is built.
pub(crate) const TABLE_LIMIT: usize = 720;
/// The largest number of cosets of a Todd–Coxeter enumeration.
const COSET_LIMIT: usize = 400_000;

pub(crate) fn identity(n: usize) -> Perm {
    (0..n).collect()
}

/// `a ∘ b`: apply `b` first.
pub(crate) fn compose(
    a: &[usize],
    b: &[usize],
) -> Perm {
    b.iter().map(|&x| a[x]).collect()
}

pub(crate) fn inverse(p: &[usize]) -> Perm {
    let mut inv = vec![0; p.len()];
    for (i, &x) in p.iter().enumerate() {
        inv[x] = i;
    }
    inv
}

pub(crate) fn is_identity(p: &[usize]) -> bool {
    p.iter().enumerate().all(|(i, &x)| i == x)
}

/// `a^-1 b^-1 a b`.
fn commutator(
    a: &[usize],
    b: &[usize],
) -> Perm {
    compose(&compose(&inverse(a), &inverse(b)), &compose(a, b))
}

/// A stabiliser chain.
#[derive(Clone, Debug)]
pub(crate) struct Chain {
    n: usize,
    base: Vec<usize>,
    gens: Vec<Vec<Perm>>,
    trans: Vec<Vec<Option<Perm>>>,
    orbit: Vec<Vec<usize>>,
}

impl Chain {
    /// The chain of the group generated by `gens` (all of degree `n`).
    pub(crate) fn new(
        n: usize,
        gens: &[Perm],
    ) -> Self {
        let mut c = Self { n, base: Vec::new(), gens: Vec::new(), trans: Vec::new(), orbit: Vec::new() };
        for g in gens {
            if !is_identity(g) {
                c.insert_generator(g);
            }
        }
        c.complete(c.base.len());
        c
    }

    fn recompute_orbit(
        &mut self,
        level: usize,
    ) {
        let b = self.base[level];
        let mut trans: Vec<Option<Perm>> = vec![None; self.n];
        trans[b] = Some(identity(self.n));
        let mut orbit = vec![b];
        let mut head = 0;
        while head < orbit.len() {
            let pt = orbit[head];
            head += 1;
            let u = trans[pt].clone().unwrap_or_default();
            for s in &self.gens[level] {
                let img = s[pt];
                if trans[img].is_none() {
                    trans[img] = Some(compose(s, &u));
                    orbit.push(img);
                }
            }
        }
        self.trans[level] = trans;
        self.orbit[level] = orbit;
    }

    /// Sifts `g` through the levels from `from` on; returns the residue and
    /// the level at which it got stuck (`base.len()` if it went through).
    fn sift(
        &self,
        mut g: Perm,
        from: usize,
    ) -> (Perm, usize) {
        for l in from..self.base.len() {
            let pt = g[self.base[l]];
            match &self.trans[l][pt] {
                | Some(u) => g = compose(&inverse(u), &g),
                | None => return (g, l),
            }
        }
        (g, self.base.len())
    }

    /// Adds the non-identity residue `r` as a strong generator of the levels
    /// `from..=to` (creating a level if `to` is the depth).
    fn add_strong(
        &mut self,
        r: &Perm,
        from: usize,
        to: usize,
    ) {
        if to == self.base.len() {
            let b = (0..self.n).find(|&x| r[x] != x).unwrap_or(0);
            self.base.push(b);
            self.gens.push(Vec::new());
            self.trans.push(Vec::new());
            self.orbit.push(Vec::new());
        }
        for m in from..=to {
            self.gens[m].push(r.clone());
            self.recompute_orbit(m);
        }
    }

    fn insert_generator(
        &mut self,
        g: &Perm,
    ) {
        let (r, j) = self.sift(g.clone(), 0);
        if !is_identity(&r) {
            self.add_strong(&r, 0, j);
        }
    }

    /// Verifies the Schreier generators from level `start - 1` upwards and
    /// repairs the chain.
    fn complete(
        &mut self,
        start: usize,
    ) {
        let mut i = start;
        while i > 0 {
            let l = i - 1;
            let mut added = None;
            'outer: for &pt in &self.orbit[l].clone() {
                for s in &self.gens[l].clone() {
                    let img = s[pt];
                    let (Some(up), Some(ui)) = (&self.trans[l][pt], &self.trans[l][img]) else { continue };
                    let h = compose(&inverse(ui), &compose(s, up));
                    let (r, j) = self.sift(h, l + 1);
                    if !is_identity(&r) {
                        self.add_strong(&r, l + 1, j);
                        added = Some(j + 1);
                        break 'outer;
                    }
                }
            }
            match added {
                | Some(next) => i = next,
                | None => i -= 1,
            }
        }
    }

    /// Adds `g` to the group.
    pub(crate) fn insert(
        &mut self,
        g: &Perm,
    ) {
        let (r, j) = self.sift(g.clone(), 0);
        if !is_identity(&r) {
            self.add_strong(&r, 0, j);
            let depth = self.base.len();
            self.complete(depth);
        }
    }

    /// Whether `g` lies in the group.
    pub(crate) fn contains(
        &self,
        g: &[usize],
    ) -> bool {
        g.len() == self.n && {
            let (r, l) = self.sift(g.to_vec(), 0);
            l == self.base.len() && is_identity(&r)
        }
    }

    pub(crate) fn order(&self) -> BigInt {
        self.orbit.iter().fold(BigInt::from(1), |acc, o| acc * o.len())
    }

    pub(crate) fn base(&self) -> &[usize] {
        &self.base
    }

    pub(crate) fn basic_orbit_lengths(&self) -> Vec<usize> {
        self.orbit.iter().map(Vec::len).collect()
    }

    /// The strong generators (without repetition), level by level.
    pub(crate) fn strong_generators(&self) -> Vec<Perm> {
        let mut seen = HashSet::new();
        let mut out = Vec::new();
        for level in &self.gens {
            for g in level {
                if seen.insert(g.clone()) {
                    out.push(g.clone());
                }
            }
        }
        out
    }

    /// The order of the stabiliser of `point`, by a chain with `point`
    /// first in the base.
    pub(crate) fn stabilizer_order(
        &self,
        point: usize,
    ) -> BigInt {
        let gens = self.strong_generators();
        let mut c = Self { n: self.n, base: Vec::new(), gens: Vec::new(), trans: Vec::new(), orbit: Vec::new() };
        // Force `point` to be the first base point by a first level with
        // (possibly) no generators moving it.
        c.base.push(point);
        c.gens.push(Vec::new());
        c.trans.push(Vec::new());
        c.orbit.push(Vec::new());
        for g in &gens {
            if !is_identity(g) {
                c.gens[0].push(g.clone());
            }
        }
        c.recompute_orbit(0);
        c.complete(1);
        // The chain was seeded with the generators at level 0 only; sift
        // them through the deeper levels to make the chain a proper one.
        let seeds = c.gens[0].clone();
        for g in &seeds {
            c.insert(g);
        }
        let total = c.order();
        total / c.orbit[0].len()
    }

    /// All elements, by products of coset representatives, if there are at
    /// most `limit`.
    pub(crate) fn elements(
        &self,
        limit: usize,
    ) -> Option<Vec<Perm>> {
        if self.order() > BigInt::from(limit) {
            return None;
        }
        let mut all = vec![identity(self.n)];
        for l in (0..self.base.len()).rev() {
            let reps: Vec<&Perm> = self.trans[l].iter().flatten().collect();
            let mut next = Vec::with_capacity(all.len() * reps.len());
            for u in reps {
                for g in &all {
                    next.push(compose(u, g));
                }
            }
            all = next;
        }
        all.sort();
        Some(all)
    }

    /// The orbits on the points, each sorted.
    pub(crate) fn orbits(&self) -> Vec<Vec<usize>> {
        let gens = self.strong_generators();
        orbits_of(self.n, &gens)
    }
}

pub(crate) fn orbits_of(
    n: usize,
    gens: &[Perm],
) -> Vec<Vec<usize>> {
    let mut seen = vec![false; n];
    let mut out = Vec::new();
    for start in 0..n {
        if seen[start] {
            continue;
        }
        let mut orbit = vec![start];
        seen[start] = true;
        let mut head = 0;
        while head < orbit.len() {
            let pt = orbit[head];
            head += 1;
            for g in gens {
                if !seen[g[pt]] {
                    seen[g[pt]] = true;
                    orbit.push(g[pt]);
                }
            }
        }
        orbit.sort_unstable();
        out.push(orbit);
    }
    out
}

/// The normal closure in `<group_gens>` of `subset`.
fn normal_closure(
    n: usize,
    group_gens: &[Perm],
    subset: &[Perm],
) -> Chain {
    let mut chain = Chain::new(n, subset);
    loop {
        let mut changed = false;
        for h in chain.strong_generators() {
            for g in group_gens {
                let c = compose(&compose(g, &h), &inverse(g));
                if !chain.contains(&c) {
                    chain.insert(&c);
                    changed = true;
                }
            }
        }
        if !changed {
            return chain;
        }
    }
}

/// The derived subgroup of `<gens>`.
pub(crate) fn derived_subgroup(
    n: usize,
    gens: &[Perm],
) -> Chain {
    let mut commutators = Vec::new();
    for (i, a) in gens.iter().enumerate() {
        for b in &gens[i + 1..] {
            commutators.push(commutator(a, b));
        }
    }
    normal_closure(n, gens, &commutators)
}

/// `[<sub>, <gens>]` for a normal subgroup `<sub>`.
fn commutator_with(
    n: usize,
    gens: &[Perm],
    sub: &[Perm],
) -> Chain {
    let mut commutators = Vec::new();
    for a in sub {
        for g in gens {
            commutators.push(commutator(a, g));
        }
    }
    normal_closure(n, gens, &commutators)
}

/// The orders of the derived series, ending at the first repeated term.
pub(crate) fn derived_series(
    n: usize,
    gens: &[Perm],
) -> Vec<BigInt> {
    let mut chain = Chain::new(n, gens);
    let mut out = vec![chain.order()];
    loop {
        let g = chain.strong_generators();
        let next = derived_subgroup(n, &g);
        let o = next.order();
        let stop = o == *out.last().unwrap_or(&o);
        if !stop {
            out.push(o);
        }
        if stop || next.order() == BigInt::from(1) {
            return out;
        }
        chain = next;
    }
}

/// The orders of the lower central series, ending at the first repeat.
pub(crate) fn lower_central_series(
    n: usize,
    gens: &[Perm],
) -> Vec<BigInt> {
    let all = Chain::new(n, gens).strong_generators();
    let mut cur = all.clone();
    let mut out = vec![Chain::new(n, &all).order()];
    loop {
        let next = commutator_with(n, &all, &cur);
        let o = next.order();
        if o == *out.last().unwrap_or(&o) {
            return out;
        }
        let trivial = o == BigInt::from(1);
        out.push(o);
        if trivial {
            return out;
        }
        cur = next.strong_generators();
    }
}

// ----------------------------------------------------------------------
// Todd–Coxeter
// ----------------------------------------------------------------------

const NONE: usize = usize::MAX;

/// A coset table under construction (HLT strategy).
struct Cosets {
    ncols: usize,
    table: Vec<usize>,
    parent: Vec<usize>,
    live: usize,
}

impl Cosets {
    fn new(ngens: usize) -> Self {
        let mut c = Self { ncols: 2 * ngens, table: Vec::new(), parent: Vec::new(), live: 0 };
        c.new_coset();
        c
    }

    fn new_coset(&mut self) -> usize {
        let id = self.parent.len();
        self.parent.push(id);
        self.table.extend(std::iter::repeat_n(NONE, self.ncols));
        self.live += 1;
        id
    }

    fn rep(
        &mut self,
        mut k: usize,
    ) -> usize {
        let mut root = k;
        while self.parent[root] != root {
            root = self.parent[root];
        }
        while self.parent[k] != root {
            let next = self.parent[k];
            self.parent[k] = root;
            k = next;
        }
        root
    }

    fn get(
        &self,
        c: usize,
        x: usize,
    ) -> usize {
        self.table[c * self.ncols + x]
    }

    fn set(
        &mut self,
        c: usize,
        x: usize,
        v: usize,
    ) {
        self.table[c * self.ncols + x] = v;
    }

    fn merge(
        &mut self,
        k: usize,
        l: usize,
        queue: &mut Vec<usize>,
    ) {
        let (k, l) = (self.rep(k), self.rep(l));
        if k != l {
            let (mu, nu) = (k.min(l), k.max(l));
            self.parent[nu] = mu;
            self.live -= 1;
            queue.push(nu);
        }
    }

    fn coincidence(
        &mut self,
        a: usize,
        b: usize,
    ) {
        let mut queue = Vec::new();
        self.merge(a, b, &mut queue);
        let mut i = 0;
        while i < queue.len() {
            let gamma = queue[i];
            i += 1;
            for x in 0..self.ncols {
                let delta = self.get(gamma, x);
                if delta == NONE {
                    continue;
                }
                self.set(delta, x ^ 1, NONE);
                let mu = self.rep(gamma);
                let nu = self.rep(delta);
                let t = self.get(mu, x);
                if t == NONE {
                    let t2 = self.get(nu, x ^ 1);
                    if t2 == NONE {
                        self.set(mu, x, nu);
                        self.set(nu, x ^ 1, mu);
                    } else {
                        self.merge(mu, t2, &mut queue);
                    }
                } else {
                    self.merge(nu, t, &mut queue);
                }
            }
        }
    }

    /// Scans the word `w` (columns) from coset `c`, defining cosets as
    /// needed.
    fn scan_and_fill(
        &mut self,
        c: usize,
        w: &[usize],
    ) -> bool {
        let (mut f, mut b) = (c, c);
        let (mut i, mut j) = (0_usize, w.len());
        // `j` is one past the last unscanned letter.
        loop {
            while i < j && self.get(f, w[i]) != NONE {
                f = self.get(f, w[i]);
                i += 1;
            }
            if i == j {
                if f != b {
                    self.coincidence(f, b);
                }
                return true;
            }
            while j > i && self.get(b, w[j - 1] ^ 1) != NONE {
                b = self.get(b, w[j - 1] ^ 1);
                j -= 1;
            }
            if j == i {
                self.coincidence(f, b);
                return true;
            }
            if j == i + 1 {
                self.set(f, w[i], b);
                self.set(b, w[i] ^ 1, f);
                return true;
            }
            if self.parent.len() >= COSET_LIMIT {
                return false;
            }
            let n = self.new_coset();
            self.set(f, w[i], n);
            self.set(n, w[i] ^ 1, f);
        }
    }
}

/// The coset table of `<gens | relators>` over the subgroup `subgens`:
/// the number of cosets and, for each generator, its action on them
/// (0-based images).
pub(crate) fn todd_coxeter_table(
    ngens: usize,
    relators: &[Vec<usize>],
    subgens: &[Vec<usize>],
) -> Option<(usize, Vec<Perm>)> {
    let mut t = Cosets::new(ngens);
    for w in subgens {
        if !t.scan_and_fill(0, w) {
            return None;
        }
    }
    let mut c = 0;
    while c < t.parent.len() {
        if t.parent[c] == c {
            for w in relators {
                if t.parent[c] != c {
                    break;
                }
                if !t.scan_and_fill(c, w) {
                    return None;
                }
            }
            if t.parent[c] == c {
                for x in 0..t.ncols {
                    if t.parent[c] == c && t.get(c, x) == NONE {
                        if t.parent.len() >= COSET_LIMIT {
                            return None;
                        }
                        let n = t.new_coset();
                        t.set(c, x, n);
                        t.set(n, x ^ 1, c);
                    }
                }
            }
        }
        c += 1;
    }
    // Compress.
    let live: Vec<usize> = (0..t.parent.len()).filter(|&k| t.parent[k] == k).collect();
    let pos: HashMap<usize, usize> = live.iter().enumerate().map(|(i, &k)| (k, i)).collect();
    let mut perms = vec![vec![0; live.len()]; ngens];
    for (i, &k) in live.iter().enumerate() {
        for (g, perm) in perms.iter_mut().enumerate() {
            let img = t.get(k, 2 * g);
            perm[i] = *pos.get(&t.rep(img))?;
        }
    }
    Some((live.len(), perms))
}

/// Reads a word over the generators `gens` into columns (`2i` for the
/// generator `i`, `2i + 1` for its inverse).
fn read_word(
    g: &Graph,
    gens: &[NodeId],
    word: NodeId,
) -> Option<Vec<usize>> {
    let letters = items(g, word)?;
    let mut out = Vec::new();
    for l in letters {
        read_letter(g, gens, l, &mut out)?;
    }
    Some(out)
}

fn read_letter(
    g: &Graph,
    gens: &[NodeId],
    l: NodeId,
    out: &mut Vec<usize>,
) -> Option<()> {
    let pos = |n: NodeId| gens.iter().position(|&s| g.same(s, n));
    if let Some(i) = pos(l) {
        out.push(2 * i);
        return Some(());
    }
    if let Some(v) = super::small(g, l) {
        let i = usize::try_from(v.unsigned_abs()).ok()?.checked_sub(1).filter(|&i| i < gens.len())?;
        out.push(2 * i + usize::from(v < 0));
        return Some(());
    }
    if g.op(l) == core::POW {
        let [b, e] = g.children(l) else { return None };
        let i = pos(*b)?;
        let k = super::small(g, *e)?;
        if k.unsigned_abs() > 10_000 {
            return None;
        }
        for _ in 0..k.unsigned_abs() {
            out.push(2 * i + usize::from(k < 0));
        }
        return Some(());
    }
    None
}

/// The number of generators, the relators and the subgroup generators.
type Presentation = (usize, Vec<Vec<usize>>, Vec<Vec<usize>>);

/// Reads a presentation: generators, relators and subgroup generators.
fn read_presentation(
    g: &Graph,
    a: &[NodeId],
) -> Option<Presentation> {
    let gens = items(g, *a.first()?)?;
    if gens.is_empty() {
        return None;
    }
    let rels: Vec<Vec<usize>> = items(g, *a.get(1)?)?.into_iter().map(|w| read_word(g, &gens, w)).collect::<Option<_>>()?;
    let subs: Vec<Vec<usize>> = match a.get(2) {
        | Some(&s) => items(g, s)?.into_iter().map(|w| read_word(g, &gens, w)).collect::<Option<_>>()?,
        | None => Vec::new(),
    };
    Some((gens.len(), rels, subs))
}

fn perm_v(p: &[usize]) -> V {
    V::ints(p.iter().map(|&x| i64::try_from(x + 1).unwrap_or(0)))
}

fn todd_coxeter(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (n, rels, subs) = read_presentation(cx.graph, a)?;
    let (index, perms) = todd_coxeter_table(n, &rels, &subs)?;
    Some(V::List(vec![V::uint(index), V::List(perms.iter().map(|p| perm_v(p)).collect())]))
}

fn todd_coxeter_index(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (n, rels, subs) = read_presentation(cx.graph, a)?;
    Some(V::uint(todd_coxeter_table(n, &rels, &subs)?.0))
}

fn fp_group_order(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (n, rels, _) = read_presentation(cx.graph, a)?;
    Some(V::uint(todd_coxeter_table(n, &rels, &[])?.0))
}

fn fp_group(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (n, rels, _) = read_presentation(cx.graph, a)?;
    let (index, perms) = todd_coxeter_table(n, &rels, &[])?;
    if index > TABLE_LIMIT {
        return None;
    }
    perm_group_term(cx.graph, index, &perms)
}

// ----------------------------------------------------------------------
// Terms
// ----------------------------------------------------------------------

/// The generators of a permutation group term: degree and permutations.
fn read_gens(
    g: &Graph,
    n: NodeId,
) -> Option<(usize, Vec<Perm>)> {
    let list = items(g, n)?;
    let mut perms = Vec::new();
    for p in list {
        perms.push(read_perm(g, p)?);
    }
    let degree = perms.first()?.len();
    if perms.iter().any(|p| p.len() != degree) || degree == 0 || degree > 64 {
        return None;
    }
    Some((degree, perms))
}

/// A permutation as 0-based images.
pub(crate) fn read_perm(
    g: &Graph,
    n: NodeId,
) -> Option<Perm> {
    let images = super::idxs(g, n)?;
    let m = images.len();
    let mut seen = vec![false; m];
    let mut out = Vec::with_capacity(m);
    for v in images {
        let v = v.checked_sub(1).filter(|&v| v < m)?;
        if std::mem::replace(&mut seen[v], true) {
            return None;
        }
        out.push(v);
    }
    Some(out)
}

fn perm_node(
    g: &mut Graph,
    p: &[usize],
) -> NodeId {
    let nodes: Vec<NodeId> = p.iter().map(|&x| g.int(i64::try_from(x + 1).unwrap_or(0))).collect();
    super::list(g, &nodes)
}

/// The group term of the permutation group generated by `gens` of degree
/// `n`, if its order is at most [`TABLE_LIMIT`].
pub(crate) fn perm_group_term(
    g: &mut Graph,
    n: usize,
    gens: &[Perm],
) -> Option<V> {
    let chain = Chain::new(n, gens);
    let elems = chain.elements(TABLE_LIMIT)?;
    let pos: HashMap<&Perm, usize> = elems.iter().enumerate().map(|(i, p)| (p, i)).collect();
    let mut table = Vec::with_capacity(elems.len());
    for p in &elems {
        let mut row = Vec::with_capacity(elems.len());
        for q in &elems {
            row.push(*pos.get(&compose(p, q))?);
        }
        table.push(row);
    }
    let nodes: Vec<NodeId> = elems.iter().map(|p| perm_node(g, p)).collect();
    build_group(g, &nodes, &table)
}

fn chain_of(
    cx: &Cx<'_>,
    a: &[NodeId],
) -> Option<Chain> {
    let (n, gens) = read_gens(cx.graph, *a.first()?)?;
    Some(Chain::new(n, &gens))
}

fn perm_group_order(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    Some(V::Int(chain_of(cx, a)?.order()))
}

fn perm_group_contains(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [gens, p] = a else { return None };
    let (n, gens) = read_gens(cx.graph, *gens)?;
    let p = read_perm(cx.graph, *p)?;
    if p.len() != n {
        return Some(V::Bool(false));
    }
    Some(V::Bool(Chain::new(n, &gens).contains(&p)))
}

fn perm_group_base(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let c = chain_of(cx, a)?;
    Some(V::ints(c.base().iter().map(|&b| i64::try_from(b + 1).unwrap_or(0))))
}

fn perm_group_strong_generators(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let c = chain_of(cx, a)?;
    Some(V::List(c.strong_generators().iter().map(|p| perm_v(p)).collect()))
}

fn perm_group_basic_orbits(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let c = chain_of(cx, a)?;
    Some(V::ints(c.basic_orbit_lengths().into_iter().map(|l| i64::try_from(l).unwrap_or(0))))
}

fn perm_group_orbits(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let c = chain_of(cx, a)?;
    Some(V::List(
        c.orbits().iter().map(|o| V::ints(o.iter().map(|&x| i64::try_from(x + 1).unwrap_or(0)))).collect(),
    ))
}

fn perm_group_is_transitive(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    Some(V::Bool(chain_of(cx, a)?.orbits().len() == 1))
}

fn perm_group_stabilizer_order(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [gens, pt] = a else { return None };
    let (n, gens) = read_gens(cx.graph, *gens)?;
    let pt = idx(cx.graph, *pt)?.checked_sub(1).filter(|&p| p < n)?;
    Some(V::Int(Chain::new(n, &gens).stabilizer_order(pt)))
}

fn perm_group_elements(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let c = chain_of(cx, a)?;
    Some(V::List(c.elements(ELEMENT_LIMIT)?.iter().map(|p| perm_v(p)).collect()))
}

fn group_from_perms(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (n, gens) = read_gens(cx.graph, *a.first()?)?;
    perm_group_term(cx.graph, n, &gens)
}

fn perm_group_is_abelian(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (_, gens) = read_gens(cx.graph, *a.first()?)?;
    Some(V::Bool(gens.iter().all(|x| gens.iter().all(|y| compose(x, y) == compose(y, x)))))
}

fn orders_v(orders: Vec<BigInt>) -> V {
    V::List(orders.into_iter().map(V::Int).collect())
}

fn perm_group_derived_series(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (n, gens) = read_gens(cx.graph, *a.first()?)?;
    Some(orders_v(derived_series(n, &gens)))
}

fn perm_group_is_solvable(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (n, gens) = read_gens(cx.graph, *a.first()?)?;
    Some(V::Bool(derived_series(n, &gens).last().is_some_and(|o| *o == BigInt::from(1))))
}

fn perm_group_lower_central_series(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (n, gens) = read_gens(cx.graph, *a.first()?)?;
    Some(orders_v(lower_central_series(n, &gens)))
}

fn perm_group_is_nilpotent(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (n, gens) = read_gens(cx.graph, *a.first()?)?;
    Some(V::Bool(lower_central_series(n, &gens).last().is_some_and(|o| *o == BigInt::from(1))))
}

fn perm_group_derived_subgroup(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (n, gens) = read_gens(cx.graph, *a.first()?)?;
    let d = derived_subgroup(n, &gens);
    let g = d.strong_generators();
    if g.is_empty() {
        return Some(V::List(vec![perm_v(&identity(n))]));
    }
    Some(V::List(g.iter().map(|p| perm_v(p)).collect()))
}

pub(crate) fn install(i: &mut Installer<'_>) -> Result<(), RuleError> {
    def(i, "perm_group_order", Arity::Fixed(1), perm_group_order)?;
    def(i, "perm_group_contains", Arity::Fixed(2), perm_group_contains)?;
    def(i, "perm_group_base", Arity::Fixed(1), perm_group_base)?;
    def(i, "perm_group_strong_generators", Arity::Fixed(1), perm_group_strong_generators)?;
    def(i, "perm_group_basic_orbits", Arity::Fixed(1), perm_group_basic_orbits)?;
    def(i, "perm_group_orbits", Arity::Fixed(1), perm_group_orbits)?;
    def(i, "perm_group_is_transitive", Arity::Fixed(1), perm_group_is_transitive)?;
    def(i, "perm_group_stabilizer_order", Arity::Fixed(2), perm_group_stabilizer_order)?;
    def(i, "perm_group_elements", Arity::Fixed(1), perm_group_elements)?;
    def(i, "group_from_perms", Arity::Fixed(1), group_from_perms)?;
    def(i, "perm_group_is_abelian", Arity::Fixed(1), perm_group_is_abelian)?;
    def(i, "perm_group_derived_series", Arity::Fixed(1), perm_group_derived_series)?;
    def(i, "perm_group_is_solvable", Arity::Fixed(1), perm_group_is_solvable)?;
    def(i, "perm_group_lower_central_series", Arity::Fixed(1), perm_group_lower_central_series)?;
    def(i, "perm_group_is_nilpotent", Arity::Fixed(1), perm_group_is_nilpotent)?;
    def(i, "perm_group_derived_subgroup", Arity::Fixed(1), perm_group_derived_subgroup)?;
    def(i, "todd_coxeter", Arity::Fixed(3), todd_coxeter)?;
    def(i, "todd_coxeter_index", Arity::Fixed(3), todd_coxeter_index)?;
    def(i, "fp_group_order", Arity::Fixed(2), fp_group_order)?;
    def(i, "fp_group", Arity::Fixed(2), fp_group)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::super::test_util::s;
    use super::*;

    fn cyc(n: usize) -> Perm {
        (0..n).map(|i| (i + 1) % n).collect()
    }

    fn swap01(n: usize) -> Perm {
        let mut p = identity(n);
        p.swap(0, 1);
        p
    }

    #[test]
    fn symmetric_groups_have_factorial_order() {
        for n in 2..=9 {
            let c = Chain::new(n, &[cyc(n), swap01(n)]);
            let fact: usize = (1..=n).product();
            assert_eq!(c.order(), BigInt::from(fact), "S{n}");
        }
        assert_eq!(Chain::new(12, &[cyc(12), swap01(12)]).order(), BigInt::from(479_001_600_u64));
    }

    #[test]
    fn mathieu_groups() {
        assert_eq!(
            s("perm_group_order(list(list(2,3,4,5,6,7,8,9,10,11,1), list(1,2,7,10,6,4,11,3,9,5,8)))"),
            "7920"
        );
        // M12 on twelve points
        let m12 = "list(list(2,3,4,5,6,7,8,9,10,11,1,12), list(1,2,7,10,6,4,11,3,9,5,8,12), list(12,11,6,8,9,3,10,4,5,7,2,1))";
        assert_eq!(s(&format!("perm_group_order({m12})")), "95040");
        assert_eq!(s(&format!("perm_group_is_transitive({m12})")), "true");
        // the point stabiliser of M12 is M11
        assert_eq!(s(&format!("perm_group_stabilizer_order({m12}, 12)")), "7920");
        assert_eq!(s(&format!("perm_group_stabilizer_order({m12}, 1)")), "7920");
        assert_eq!(s(&format!("perm_group_is_solvable({m12})")), "false");
        assert_eq!(s(&format!("perm_group_derived_series({m12})")), "list(95040)");
    }

    #[test]
    fn membership_and_base() {
        let a4 = "list(list(2,3,1,4), list(1,3,4,2))";
        assert_eq!(s(&format!("perm_group_order({a4})")), "12");
        assert_eq!(s(&format!("perm_group_contains({a4}, list(2,1,4,3))")), "true");
        assert_eq!(s(&format!("perm_group_contains({a4}, list(2,1,3,4))")), "false");
        assert_eq!(s(&format!("perm_group_contains({a4}, list(1,2,3))")), "false");
        let c = Chain::new(4, &[vec![1, 2, 0, 3], vec![0, 2, 3, 1]]);
        // the product of the basic orbit lengths is the order
        assert_eq!(c.basic_orbit_lengths().iter().product::<usize>(), 12);
        assert!(c.base().len() >= 2);
        // the base has trivial pointwise stabiliser
        for g in c.elements(100).unwrap_or_default() {
            if c.base().iter().all(|&b| g[b] == b) {
                assert!(is_identity(&g));
            }
        }
        assert_eq!(s(&format!("perm_group_base({a4})")), "list(1, 2)");
    }

    #[test]
    fn elements_and_tables() {
        assert_eq!(s("perm_group_order(list(list(2,3,1), list(2,1,3)))"), "6");
        let e = s("perm_group_elements(list(list(2,3,1)))");
        assert_eq!(e, "list(list(1, 2, 3), list(2, 3, 1), list(3, 1, 2))");
        assert_eq!(s("group_order(group_from_perms(list(list(2,3,4,1), list(1,4,3,2))))"), "8");
        assert_eq!(s("group_is_valid(group_from_perms(list(list(2,3,4,1), list(1,4,3,2))))"), "true");
        assert_eq!(s("perm_group_orbits(list(list(2,1,3,5,4)))"), "list(list(1, 2), list(3), list(4, 5))");
    }

    #[test]
    fn solvability_and_nilpotency() {
        // S4: derived series 24 > 12 > 4 > 1, lower central series 24 > 12
        let s4 = "list(list(2,3,4,1), list(2,1,3,4))";
        assert_eq!(s(&format!("perm_group_derived_series({s4})")), "list(24, 12, 4, 1)");
        assert_eq!(s(&format!("perm_group_is_solvable({s4})")), "true");
        assert_eq!(s(&format!("perm_group_lower_central_series({s4})")), "list(24, 12)");
        assert_eq!(s(&format!("perm_group_is_nilpotent({s4})")), "false");
        // S5 is not solvable; A5 is perfect
        let s5 = "list(list(2,3,4,5,1), list(2,1,3,4,5))";
        assert_eq!(s(&format!("perm_group_derived_series({s5})")), "list(120, 60)");
        assert_eq!(s(&format!("perm_group_is_solvable({s5})")), "false");
        // D4 is nilpotent of class 2
        let d4 = "list(list(2,3,4,1), list(1,4,3,2))";
        assert_eq!(s(&format!("perm_group_lower_central_series({d4})")), "list(8, 2, 1)");
        assert_eq!(s(&format!("perm_group_is_nilpotent({d4})")), "true");
        assert_eq!(s(&format!("perm_group_derived_series({d4})")), "list(8, 2, 1)");
        assert_eq!(s(&format!("perm_group_is_abelian({d4})")), "false");
        assert_eq!(s("perm_group_is_abelian(list(list(2,1,3,4), list(1,2,4,3)))"), "true");
        assert!(s(&format!("perm_group_derived_subgroup({s4})")).matches("list(").count() >= 2);
    }

    #[test]
    fn todd_coxeter_basics() {
        // <a, b | a^3, b^2, (ab)^2> = S3
        assert_eq!(s("todd_coxeter_index(list(a, b), list(list(a, a, a), list(b, b), list(a, b, a, b)), list())"), "6");
        assert_eq!(s("fp_group_order(list(a, b), list(list(a^3), list(b^2), list(a, b, a, b)))"), "6");
        // over the subgroup <b> the index is 3
        assert_eq!(
            s("todd_coxeter_index(list(a, b), list(list(a, a, a), list(b, b), list(a, b, a, b)), list(list(b)))"),
            "3"
        );
        // the action is a permutation representation of degree 3
        let act = s("todd_coxeter(list(a, b), list(list(a, a, a), list(b, b), list(a, b, a, b)), list(list(b)))");
        assert!(act.starts_with("list(3, list(list("), "{act}");
        // Z4 x Z2 and the quaternion group Q8
        assert_eq!(s("fp_group_order(list(a, b), list(list(a^4), list(b^2), list(a, b, -1, -2)))"), "8");
        assert_eq!(s("fp_group_order(list(a, b), list(list(a^4), list(a, a, -2, -2), list(b, a, -2, a)))"), "8");
        // the trivial and the free abelian quotient
        assert_eq!(s("fp_group_order(list(a), list(list(a)))"), "1");
        assert_eq!(s("fp_group_order(list(a), list(list(a^12)))"), "12");
        // an infinite group exceeds the coset limit and stays unreduced
        assert_eq!(s("fp_group_order(list(a), list())"), "fp_group_order(list(a), list())");
    }

    #[test]
    fn fp_group_is_a_group_term() {
        let g = "fp_group(list(a, b), list(list(a^3), list(b^2), list(a, b, a, b)))";
        assert_eq!(s(&format!("group_order({g})")), "6");
        assert_eq!(s(&format!("group_is_abelian({g})")), "false");
        assert_eq!(s(&format!("group_is_valid({g})")), "true");
    }

    #[test]
    fn psl27() {
        // PSL(2,7) = <a, b | a^2, b^3, (ab)^7, [a,b]^4> of order 168
        let words: Vec<Vec<usize>> = vec![
            vec![0, 0],
            vec![2, 2, 2],
            std::iter::repeat_n([0, 2], 7).flatten().collect(),
            std::iter::repeat_n([0, 2, 1, 3], 4).flatten().collect(),
        ];
        // here columns: a = 0, a^-1 = 1, b = 2, b^-1 = 3; b^3 = (2,2,2)
        let (index, perms) = todd_coxeter_table(2, &words, &[]).unwrap_or((0, Vec::new()));
        assert_eq!(index, 168);
        assert_eq!(perms.len(), 2);
    }
}
