//! Character theory of finite groups.
//!
//! The character table of a group is computed by the **Burnside–Dixon
//! algorithm**: the class multiplication constants give commuting *class
//! matrices* whose simultaneous eigenvectors are the central characters
//! `|C_i| chi(g_i) / chi(1)`. The eigenproblem is solved over the finite field
//! `F_p` with `p > |G|` and `p = 1 (mod exp G)`, where every eigenvalue
//! exists and the degrees come out as exact integers (`chi(1)^2 = |G| / S`).
//! The values are then lifted *exactly* to cyclotomic integers: restricting
//! to the cyclic group generated by a class representative `g` of order `m`,
//! the multiplicity of the eigenvalue `zeta_m^j` of `chi(g)` is
//! `(1/m) sum_t chi(g^t) zeta_m^(-jt)`, an integer in `0..=chi(1)` that is read
//! off modulo `p`. So every entry is a sum of roots of unity, e.g.
//! `exp(2*pi*I/3)`, and real quadratic entries such as the golden ratio
//! `(1 + sqrt(5))/2` of `A5` are recognised and written with radicals. The
//! table is verified by exact (numerical to `1e-8`) orthogonality before it
//! is returned.
//!
//! Rows are ordered by degree, then by decreasing values over the classes of
//! [`group_conjugacy_classes`](super::groups), so the trivial character
//! comes first. Columns follow the class order of `group_conjugacy_classes`.
//!
//! A *class function* is given as a list with one value per class (or one
//! value per group element); values may be any numeric terms, including
//! `exp(2*pi*I/3)`.
//!
//! | operator | value |
//! |---|---|
//! | `group_class_count(G)`, `group_class_sizes(G)`, `group_class_representatives(G)` | class data |
//! | `group_class_index(G, x)` | the 1-based index of the class of `x` |
//! | `group_character_table(G)` | list of the irreducible characters, one list of class values each |
//! | `group_character_degrees(G)` | their degrees |
//! | `character_table_is_orthogonal(G)` | row and column orthogonality of the computed table |
//! | `character_inner_product(G, chi, psi)` | `(1/|G|) sum chi(g) conj(psi(g))` |
//! | `character_is_irreducible(G, chi)` | `<chi, chi> = 1` |
//! | `character_decompose(G, chi)` | the multiplicities of the irreducibles (rows of the table) |
//! | `character_tensor(G, chi, psi)` | the pointwise product (tensor product) |
//! | `character_sym_square(G, chi)`, `character_alt_square(G, chi)` | `(chi(g)^2 + chi(g^2))/2`, `(chi(g)^2 - chi(g^2))/2` |
//! | `character_adams(G, chi, k)` | the Adams operation `g -> chi(g^k)` |
//! | `character_conjugate(G, chi)` | complex conjugate |
//! | `character_regular(G)` | the character of the regular representation |
//! | `character_of_matrices(G, mats)` | the class function of a matrix representation (traces at class representatives) |
//! | `representation_decompose(G, mats)` | its multiplicities of the irreducibles |
//! | `character_projection(G, i, mats)` | the projection `(d_i/|G|) sum conj(chi_i(g)) M(g)` onto the `i`-th isotypic component |

// Index loops over several parallel tables and float comparisons with explicit
// tolerances read better than the iterator forms; `as` casts convert small,
// non-negative, bounded values.
#![allow(
    clippy::needless_range_loop,
    clippy::float_cmp,
    clippy::cast_sign_loss,
    clippy::manual_midpoint
)]

use std::collections::HashMap;

use num_complex::Complex64;
use num_integer::Integer;

use super::apply;
use super::def;
use super::group_theory::tab_of;
use super::group_theory::Tab;
use super::groups::lookup;
use super::idx;
use super::items;
use super::prod;
use super::rows;
use super::sum;
use super::V;
use crate::graph::rule::Installer;
use crate::graph::Arity;
use crate::graph::Cx;
use crate::graph::Graph;
use crate::graph::NodeId;
use crate::graph::Number;
use crate::graph::RuleError;

// ----------------------------------------------------------------------
// Modular arithmetic
// ----------------------------------------------------------------------

const fn mpow(
    mut b: u64,
    mut e: u64,
    p: u64,
) -> u64 {
    let mut r = 1;
    b %= p;
    while e > 0 {
        if e & 1 == 1 {
            r = r * b % p;
        }
        b = b * b % p;
        e >>= 1;
    }
    r
}

const fn minv(
    a: u64,
    p: u64,
) -> u64 {
    mpow(a, p - 2, p)
}

fn is_prime(n: u64) -> bool {
    n >= 2 && (2..n).take_while(|d| d * d <= n).all(|d| !n.is_multiple_of(d))
}

/// The null vector of the `k x k` matrix `a` modulo `p`, if the null space is
/// one-dimensional.
fn null_vector(
    mut a: Vec<Vec<u64>>,
    p: u64,
) -> Option<Vec<u64>> {
    let k = a.len();
    let mut pivots = Vec::new();
    let mut row = 0;
    for col in 0..k {
        let Some(r) = (row..k).find(|&r| a[r][col] != 0) else { continue };
        a.swap(row, r);
        let inv = minv(a[row][col], p);
        for x in &mut a[row] {
            *x = *x * inv % p;
        }
        for r2 in 0..k {
            if r2 != row && a[r2][col] != 0 {
                let f = a[r2][col];
                for c in 0..k {
                    a[r2][c] = (a[r2][c] + p - f * a[row][c] % p) % p;
                }
            }
        }
        pivots.push(col);
        row += 1;
    }
    if pivots.len() != k - 1 {
        return None;
    }
    let free = (0..k).find(|c| !pivots.contains(c))?;
    let mut v = vec![0; k];
    v[free] = 1;
    for (r, &pc) in pivots.iter().enumerate() {
        v[pc] = (p - a[r][free]) % p;
    }
    Some(v)
}

/// The characteristic polynomial coefficients (`c[i]` of `x^i`) of a matrix
/// modulo `p` (Faddeev–LeVerrier).
fn charpoly(
    a: &[Vec<u64>],
    p: u64,
) -> Vec<u64> {
    let k = a.len();
    let mut coeffs = vec![0; k + 1];
    coeffs[k] = 1;
    let mut m = vec![vec![0_u64; k]; k];
    for i in 1..=k {
        // m = a * m + c_{k-i+1} I
        let mut next = vec![vec![0_u64; k]; k];
        for r in 0..k {
            for c in 0..k {
                let mut s = 0;
                for t in 0..k {
                    s = (s + a[r][t] * m[t][c]) % p;
                }
                next[r][c] = s;
            }
            next[r][r] = (next[r][r] + coeffs[k - i + 1]) % p;
        }
        m = next;
        // c_{k-i} = -(1/i) tr(a m)
        let mut tr = 0;
        for r in 0..k {
            for t in 0..k {
                tr = (tr + a[r][t] * m[t][r]) % p;
            }
        }
        let inv = minv(i as u64, p);
        coeffs[k - i] = (p - tr * inv % p) % p;
    }
    coeffs
}

fn eval_poly(
    c: &[u64],
    x: u64,
    p: u64,
) -> u64 {
    c.iter().rev().fold(0, |acc, &co| (acc * x + co) % p)
}

// ----------------------------------------------------------------------
// Cyclotomic values
// ----------------------------------------------------------------------

/// A character value: the sum of `v[k]` copies of `exp(2 pi i k / m)`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct Entry {
    pub(crate) m: usize,
    pub(crate) v: Vec<i64>,
}

impl Entry {
    pub(crate) fn value(&self) -> Complex64 {
        let m = self.m as f64;
        self.v
            .iter()
            .enumerate()
            .map(|(k, &c)| Complex64::from_polar(1.0, 2.0 * std::f64::consts::PI * k as f64 / m) * c as f64)
            .sum()
    }

    fn conj(&self) -> Self {
        let mut v = vec![0; self.m];
        for (k, &c) in self.v.iter().enumerate() {
            v[(self.m - k) % self.m] = c;
        }
        Self { m: self.m, v }
    }
}

/// The cyclotomic polynomial `Phi_m` as integer coefficients (low first).
fn cyclotomic(m: usize) -> Vec<i64> {
    let mut num = vec![0_i64; m + 1];
    num[0] = -1;
    num[m] = 1;
    for d in 1..m {
        if m.is_multiple_of(d) {
            let phi = cyclotomic(d);
            num = poly_div(&num, &phi);
        }
    }
    num
}

/// Exact division of integer polynomials by a monic divisor.
fn poly_div(
    a: &[i64],
    b: &[i64],
) -> Vec<i64> {
    let mut rem = a.to_vec();
    let (da, db) = (a.len() - 1, b.len() - 1);
    if da < db {
        return vec![0];
    }
    let mut q = vec![0; da - db + 1];
    for i in (0..=da - db).rev() {
        let c = rem[i + db];
        q[i] = c;
        for (j, &bj) in b.iter().enumerate() {
            rem[i + j] -= c * bj;
        }
    }
    q
}

/// Reduces an entry's coefficient vector by shifts of `Phi_m` while the
/// sum of absolute values decreases.
fn minimise(e: &Entry) -> Entry {
    let m = e.m;
    if m < 2 {
        return e.clone();
    }
    let phi = cyclotomic(m);
    let mut v = e.v.clone();
    let l1 = |v: &[i64]| v.iter().map(|c| c.abs()).sum::<i64>();
    loop {
        let mut best: Option<(i64, Vec<i64>)> = None;
        for shift in 0..m {
            for sign in [1_i64, -1] {
                let mut cand = v.clone();
                for (j, &c) in phi.iter().enumerate() {
                    cand[(j + shift) % m] += sign * c;
                }
                let n = l1(&cand);
                if n < best.as_ref().map_or_else(|| l1(&v), |b| b.0) {
                    best = Some((n, cand));
                }
            }
        }
        match best {
            | Some((_, cand)) => v = cand,
            | None => return Entry { m, v },
        }
    }
}

/// `(a + b sqrt(d)) / c` close to `x`, with `d` squarefree.
fn recognise_quadratic(x: f64) -> Option<(i64, i64, i64, i64)> {
    for c in [1_i64, 2, 3, 4, 6, 8, 12] {
        for d in [1_i64, 2, 3, 5, 6, 7, 10, 11, 13, 15] {
            let sq = (d as f64).sqrt();
            let max_b = if d == 1 { 0 } else { 24 };
            for bb in 0..=max_b {
                for b in if bb == 0 { vec![0] } else { vec![bb, -bb] } {
                    let a = (x * c as f64 - b as f64 * sq).round();
                    if (a + b as f64 * sq - x * c as f64).abs() < 1e-9 && a.abs() < 1e6 {
                        let a = a as i64;
                        let g = a.gcd(&b).gcd(&c);
                        let g = if g == 0 { 1 } else { g };
                        return Some((a / g, b / g, d, c / g));
                    }
                }
            }
        }
    }
    None
}

fn rat_node(
    g: &mut Graph,
    p: i64,
    q: i64,
) -> NodeId {
    match Number::fraction(p, q) {
        | Some(n) => g.num(n),
        | None => g.int(0),
    }
}

/// The exact term of a character value.
pub(crate) fn entry_node(
    g: &mut Graph,
    e: &Entry,
) -> NodeId {
    let e = minimise(e);
    let z = e.value();
    let nonzero: Vec<(usize, i64)> = e.v.iter().copied().enumerate().filter(|&(_, c)| c != 0).collect();
    if nonzero.is_empty() {
        return g.int(0);
    }
    if nonzero.len() == 1 && nonzero[0].0 == 0 {
        return g.int(nonzero[0].1);
    }
    if z.im.abs() < 1e-9
        && let Some((a, b, d, c)) = recognise_quadratic(z.re) {
            let mut terms = vec![rat_node(g, a, c)];
            if b != 0 {
                let dn = g.int(d);
                let sq = apply(g, "sqrt", &[dn]);
                if let Some(sq) = sq {
                    let coef = rat_node(g, b, c);
                    terms.push(prod(g, &[coef, sq]));
                }
            }
            return sum(g, &terms);
        }
    let pi = apply(g, "pi", &[]);
    let unit = apply(g, "I", &[]);
    let mut terms = Vec::new();
    for (k, c) in nonzero {
        // exp(2 pi i k / m), with k reduced to (-m/2, m/2]
        let m = e.m as i64;
        let mut kk = k as i64;
        if 2 * kk > m {
            kk -= m;
        }
        let exp = match (pi, unit) {
            | (Some(pi), Some(unit)) => {
                let q = rat_node(g, 2 * kk, m);
                let arg = prod(g, &[q, pi, unit]);
                apply(g, "exp", &[arg])
            },
            | _ => None,
        };
        let Some(exp) = exp else { return g.float(z.re) };
        if kk == 0 {
            terms.push(g.int(c));
        } else {
            let cn = g.int(c);
            terms.push(prod(g, &[cn, exp]));
        }
    }
    sum(g, &terms)
}

// ----------------------------------------------------------------------
// The character table
// ----------------------------------------------------------------------

/// The character table of a group.
pub(crate) struct CharTable {
    pub(crate) classes: Vec<Vec<usize>>,
    pub(crate) class_of: Vec<usize>,
    pub(crate) reps: Vec<usize>,
    pub(crate) sizes: Vec<usize>,
    pub(crate) degrees: Vec<usize>,
    pub(crate) rows: Vec<Vec<Entry>>,
    pub(crate) z: Vec<Vec<Complex64>>,
    pub(crate) inv_class: Vec<usize>,
    pub(crate) n: usize,
}

impl CharTable {
    /// `(1/|G|) sum_g a(g) conj(b(g))` over class functions.
    pub(crate) fn inner(
        &self,
        a: &[Complex64],
        b: &[Complex64],
    ) -> Complex64 {
        let s: Complex64 = (0..self.classes.len()).map(|i| a[i] * b[i].conj() * self.sizes[i] as f64).sum();
        s / self.n as f64
    }

    /// The multiplicities of the irreducibles in a class function.
    pub(crate) fn decompose(
        &self,
        chi: &[Complex64],
    ) -> Option<Vec<i64>> {
        self.z
            .iter()
            .map(|row| {
                let m = self.inner(chi, row);
                let r = m.re.round();
                (m.im.abs() < 1e-6 && (m.re - r).abs() < 1e-6).then_some(r as i64)
            })
            .collect()
    }
}

/// Class function values from a list of terms: one per class or per element.
pub(crate) fn read_class_function(
    g: &Graph,
    ct: &CharTable,
    n: NodeId,
) -> Option<Vec<Complex64>> {
    let list = items(g, n)?;
    let bindings = HashMap::new();
    let vals: Vec<Complex64> = list.iter().map(|&x| g.eval_complex(x, &bindings)).collect::<Option<_>>()?;
    if vals.len() == ct.classes.len() {
        Some(vals)
    } else if vals.len() == ct.n {
        Some(ct.reps.iter().map(|&r| vals[r]).collect())
    } else {
        None
    }
}

fn find_prime(
    n: usize,
    e: usize,
    k: usize,
) -> u64 {
    let lower = (n as u64).max(16 * (k * k) as u64);
    let mut j = 1;
    loop {
        let p = (e * j + 1) as u64;
        if p > lower && is_prime(p) {
            return p;
        }
        j += 1;
    }
}

fn isqrt_exact(v: u64) -> Option<u64> {
    let r = (v as f64).sqrt().round() as u64;
    (r.saturating_sub(1)..=r + 1).find(|&c| c * c == v)
}

/// The character table of the group with multiplication table `t`.
#[allow(clippy::too_many_lines)] // one algorithm: constants, eigenvectors, degrees, lifting
pub(crate) fn character_table(t: &Tab) -> Option<CharTable> {
    let n = t.n;
    let classes = t.classes();
    let k = classes.len();
    let mut class_of = vec![0; n];
    for (i, c) in classes.iter().enumerate() {
        for &x in c {
            class_of[x] = i;
        }
    }
    let reps: Vec<usize> = classes.iter().map(|c| c[0]).collect();
    let sizes: Vec<usize> = classes.iter().map(Vec::len).collect();
    let inv_class: Vec<usize> = reps.iter().map(|&r| class_of[t.inv[r]]).collect();
    let id_class = class_of[t.id];
    let e = (0..n).fold(1, |acc, x| acc.lcm(&t.order(x)));
    let p = find_prime(n, e, k);

    // Class multiplication constants a[j][i][l] = #{(x, y) in C_i x C_j : xy = z_l}.
    let mut a = vec![vec![vec![0_u64; k]; k]; k];
    for (l, &z) in reps.iter().enumerate() {
        for x in 0..n {
            let y = t.m(t.inv[x], z);
            a[class_of[y]][class_of[x]][l] += 1;
        }
    }
    // Eigen-decomposition of a random combination of the class matrices.
    let mut seed = 0x9E37_79B9_7F4A_7C15_u64;
    let mut next = || {
        seed = seed.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1_442_695_040_888_963_407);
        (seed >> 33) % p
    };
    let mut omegas: Option<Vec<Vec<u64>>> = None;
    for attempt in 0..60 {
        let coeffs: Vec<u64> = (0..k).map(|j| if attempt == 0 { j as u64 + 1 } else { next() }).collect();
        let mut m = vec![vec![0_u64; k]; k];
        for j in 0..k {
            for i in 0..k {
                for l in 0..k {
                    m[i][l] = (m[i][l] + coeffs[j] * a[j][i][l]) % p;
                }
            }
        }
        let cp = charpoly(&m, p);
        let roots: Vec<u64> = (0..p).filter(|&x| eval_poly(&cp, x, p) == 0).collect();
        if roots.len() != k {
            continue;
        }
        let mut vecs = Vec::new();
        for &lam in &roots {
            let mut shifted = m.clone();
            for (i, row) in shifted.iter_mut().enumerate() {
                row[i] = (row[i] + p - lam) % p;
            }
            let Some(mut w) = null_vector(shifted, p) else { break };
            if w[id_class] == 0 {
                break;
            }
            let inv = minv(w[id_class], p);
            for x in &mut w {
                *x = *x * inv % p;
            }
            vecs.push(w);
        }
        if vecs.len() == k {
            omegas = Some(vecs);
            break;
        }
    }
    let omegas = omegas?;

    // A primitive e-th root of unity modulo p.
    let primes: Vec<u64> = (2..=e as u64).filter(|&q| (e as u64).is_multiple_of(q) && is_prime(q)).collect();
    let root_e = (2..p)
        .map(|h| mpow(h, (p - 1) / e as u64, p))
        .find(|&r| mpow(r, e as u64, p) == 1 && primes.iter().all(|&q| mpow(r, e as u64 / q, p) != 1))
        .unwrap_or(1);

    let mut rows_raw: Vec<(usize, Vec<Entry>)> = Vec::new();
    for w in &omegas {
        // chi(1)^2 = |G| / sum_i w_i w_{i'} / |C_i|
        let mut s = 0;
        for i in 0..k {
            let term = w[i] * w[inv_class[i]] % p * minv(sizes[i] as u64 % p, p) % p;
            s = (s + term) % p;
        }
        let d2 = n as u64 % p * minv(s, p) % p;
        let d = isqrt_exact(d2)?;
        let chi_p: Vec<u64> = (0..k).map(|i| d % p * w[i] % p * minv(sizes[i] as u64 % p, p) % p).collect();
        let mut entries = Vec::with_capacity(k);
        for i in 0..k {
            let g = reps[i];
            let m = t.order(g);
            let omega_m = mpow(root_e, (e / m) as u64, p);
            let inv_m = minv(m as u64 % p, p);
            let mut v_m = vec![0_i64; m];
            let mut total = 0;
            for j in 0..m {
                let mut acc = 0;
                for tt in 0..m {
                    let val = chi_p[class_of[t.pow(g, tt)]];
                    let root = mpow(omega_m, ((m - j) * tt % m) as u64, p);
                    acc = (acc + val * root) % p;
                }
                let mult = acc * inv_m % p;
                if mult > d {
                    return None;
                }
                v_m[j] = mult as i64;
                total += mult;
            }
            if total != d {
                return None;
            }
            entries.push(Entry { m, v: v_m });
        }
        rows_raw.push((d as usize, entries));
    }
    let mut rows: Vec<(usize, Vec<Entry>, Vec<Complex64>)> = rows_raw
        .into_iter()
        .map(|(d, es)| {
            let z: Vec<Complex64> = es.iter().map(Entry::value).collect();
            (d, es, z)
        })
        .collect();
    rows.sort_by(|x, y| {
        x.0.cmp(&y.0).then_with(|| {
            for (a, b) in x.2.iter().zip(&y.2) {
                let (ra, rb) = ((a.re * 1e6).round(), (b.re * 1e6).round());
                if ra != rb {
                    return rb.total_cmp(&ra);
                }
                let (ia, ib) = ((a.im * 1e6).round(), (b.im * 1e6).round());
                if ia != ib {
                    return ib.total_cmp(&ia);
                }
            }
            std::cmp::Ordering::Equal
        })
    });
    let table = CharTable {
        classes,
        class_of,
        reps,
        sizes,
        degrees: rows.iter().map(|r| r.0).collect(),
        z: rows.iter().map(|r| r.2.clone()).collect(),
        rows: rows.into_iter().map(|r| r.1).collect(),
        inv_class,
        n,
    };
    table.verify().then_some(table)
}

impl CharTable {
    /// Row and column orthogonality, and `sum d^2 = |G|`.
    pub(crate) fn verify(&self) -> bool {
        let k = self.classes.len();
        if self.degrees.iter().map(|d| d * d).sum::<usize>() != self.n || self.z.len() != k {
            return false;
        }
        for (a, ra) in self.z.iter().enumerate() {
            for (b, rb) in self.z.iter().enumerate() {
                let ip = self.inner(ra, rb);
                let want = if a == b { 1.0 } else { 0.0 };
                if (ip.re - want).abs() > 1e-8 || ip.im.abs() > 1e-8 {
                    return false;
                }
            }
        }
        for i in 0..k {
            for j in 0..k {
                let s: Complex64 = self.z.iter().map(|r| r[i] * r[j].conj()).sum();
                let want = if i == j { self.n as f64 / self.sizes[i] as f64 } else { 0.0 };
                if (s.re - want).abs() > 1e-8 || s.im.abs() > 1e-8 {
                    return false;
                }
            }
        }
        true
    }

    /// The class of the `k`-th power of the elements of each class.
    pub(crate) fn power_classes(
        &self,
        t: &Tab,
        k: usize,
    ) -> Vec<usize> {
        self.reps.iter().map(|&r| self.class_of[t.pow(r, k)]).collect()
    }
}

// ----------------------------------------------------------------------
// Operators
// ----------------------------------------------------------------------

fn table_of(
    cx: &mut Cx<'_>,
    n: NodeId,
) -> Option<(super::groups::Grp, Tab, CharTable)> {
    let (grp, t) = tab_of(cx, n)?;
    let ct = character_table(&t)?;
    Some((grp, t, ct))
}

fn classes_of(
    cx: &mut Cx<'_>,
    n: NodeId,
) -> Option<(super::groups::Grp, Tab, Vec<Vec<usize>>)> {
    let (grp, t) = tab_of(cx, n)?;
    let classes = t.classes();
    Some((grp, t, classes))
}

fn group_class_count(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (_, _, c) = classes_of(cx, *a.first()?)?;
    Some(V::uint(c.len()))
}

fn group_class_sizes(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (_, _, c) = classes_of(cx, *a.first()?)?;
    Some(V::List(c.iter().map(|x| V::uint(x.len())).collect()))
}

fn group_class_representatives(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (grp, _, c) = classes_of(cx, *a.first()?)?;
    Some(V::List(c.iter().map(|x| V::Node(grp.elems[x[0]])).collect()))
}

fn group_class_index(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [g, x] = a else { return None };
    let (grp, _, c) = classes_of(cx, *g)?;
    let x = lookup(cx, &grp.index, *x)?;
    Some(V::uint(c.iter().position(|cl| cl.contains(&x))? + 1))
}

fn table_nodes(
    g: &mut Graph,
    ct: &CharTable,
) -> V {
    V::List(
        ct.rows
            .iter()
            .map(|row| V::List(row.iter().map(|e| V::Node(entry_node(g, e))).collect()))
            .collect(),
    )
}

fn group_character_table(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (_, _, ct) = table_of(cx, *a.first()?)?;
    Some(table_nodes(cx.graph, &ct))
}

fn group_character_degrees(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (_, _, ct) = table_of(cx, *a.first()?)?;
    Some(V::List(ct.degrees.iter().map(|&d| V::uint(d)).collect()))
}

fn character_table_is_orthogonal(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (_, t) = tab_of(cx, *a.first()?)?;
    Some(V::Bool(character_table(&t).is_some()))
}

fn two_functions(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<(CharTable, Vec<Complex64>, Vec<Complex64>)> {
    let [g, x, y] = a else { return None };
    let (_, _, ct) = table_of(cx, *g)?;
    let x = read_class_function(cx.graph, &ct, *x)?;
    let y = read_class_function(cx.graph, &ct, *y)?;
    Some((ct, x, y))
}

fn character_inner_product(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (ct, x, y) = two_functions(cx, a)?;
    let ip = ct.inner(&x, &y);
    if (ip.im).abs() > 1e-9 {
        return None;
    }
    let scaled = ip.re * ct.n as f64;
    if (scaled - scaled.round()).abs() > 1e-7 {
        return Some(V::Float(ip.re));
    }
    let num = scaled.round() as i64;
    let den = ct.n as i64;
    let g = num.gcd(&den);
    let (num, den) = (num / g, den / g);
    if den == 1 {
        Some(V::int(num))
    } else {
        let node = rat_node(cx.graph, num, den);
        Some(V::Node(node))
    }
}

fn character_is_irreducible(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [g, x] = a else { return None };
    let (_, _, ct) = table_of(cx, *g)?;
    let x = read_class_function(cx.graph, &ct, *x)?;
    let ip = ct.inner(&x, &x);
    Some(V::Bool((ip.re - 1.0).abs() < 1e-6 && ip.im.abs() < 1e-6))
}

fn character_decompose(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [g, x] = a else { return None };
    let (_, _, ct) = table_of(cx, *g)?;
    let x = read_class_function(cx.graph, &ct, *x)?;
    Some(V::ints(ct.decompose(&x)?))
}

fn class_nodes(
    cx: &Cx<'_>,
    ct: &CharTable,
    n: NodeId,
) -> Option<Vec<NodeId>> {
    let list = items(cx.graph, n)?;
    if list.len() == ct.classes.len() {
        Some(list)
    } else if list.len() == ct.n {
        Some(ct.reps.iter().map(|&r| list[r]).collect())
    } else {
        None
    }
}

fn simplified_list(
    cx: &mut Cx<'_>,
    nodes: Vec<NodeId>,
) -> V {
    V::List(nodes.into_iter().map(|x| V::Node(cx.simplify(x))).collect())
}

fn character_tensor(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [g, x, y] = a else { return None };
    let (_, _, ct) = table_of(cx, *g)?;
    let (x, y) = (class_nodes(cx, &ct, *x)?, class_nodes(cx, &ct, *y)?);
    let prods: Vec<NodeId> = x.iter().zip(&y).map(|(&p, &q)| prod(cx.graph, &[p, q])).collect();
    Some(simplified_list(cx, prods))
}

fn square(
    cx: &mut Cx<'_>,
    a: &[NodeId],
    sign: i64,
) -> Option<V> {
    let [g, x] = a else { return None };
    let (_, t, ct) = table_of(cx, *g)?;
    let x = class_nodes(cx, &ct, *x)?;
    let sq = ct.power_classes(&t, 2);
    let half = rat_node(cx.graph, 1, 2);
    let s = cx.graph.int(sign);
    let mut out = Vec::new();
    for i in 0..x.len() {
        let two = cx.graph.int(2);
        let chi2 = super::pow(cx.graph, x[i], two);
        let rot = prod(cx.graph, &[s, x[sq[i]]]);
        let inner = sum(cx.graph, &[chi2, rot]);
        out.push(prod(cx.graph, &[half, inner]));
    }
    Some(simplified_list(cx, out))
}

fn character_sym_square(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    square(cx, a, 1)
}

fn character_alt_square(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    square(cx, a, -1)
}

fn character_adams(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [g, x, k] = a else { return None };
    let k = idx(cx.graph, *k)?;
    let (_, t, ct) = table_of(cx, *g)?;
    let x = class_nodes(cx, &ct, *x)?;
    let pc = ct.power_classes(&t, k);
    Some(V::List(pc.iter().map(|&c| V::Node(x[c])).collect()))
}

fn character_conjugate(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [g, x] = a else { return None };
    let (_, _, ct) = table_of(cx, *g)?;
    let x = class_nodes(cx, &ct, *x)?;
    let mut out = Vec::new();
    for v in x {
        let c = apply(cx.graph, "conj", &[v])?;
        out.push(c);
    }
    Some(simplified_list(cx, out))
}

fn character_regular(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (_, t, classes) = classes_of(cx, *a.first()?)?;
    Some(V::List(
        classes.iter().map(|c| if c[0] == t.id { V::uint(t.n) } else { V::int(0) }).collect(),
    ))
}

fn matrices(
    g: &Graph,
    n: NodeId,
) -> Option<Vec<Vec<Vec<NodeId>>>> {
    items(g, n)?.into_iter().map(|m| rows(g, m)).collect()
}

fn trace_node(
    cx: &mut Cx<'_>,
    m: &[Vec<NodeId>],
) -> Option<NodeId> {
    if m.iter().any(|r| r.len() != m.len()) {
        return None;
    }
    let diag: Vec<NodeId> = m.iter().enumerate().map(|(i, r)| r[i]).collect();
    let t = sum(cx.graph, &diag);
    Some(cx.simplify(t))
}

fn character_of_matrices(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [g, m] = a else { return None };
    let (_, t, classes) = classes_of(cx, *g)?;
    let mats = matrices(cx.graph, *m)?;
    if mats.len() != t.n {
        return None;
    }
    let mut out = Vec::new();
    for c in &classes {
        out.push(V::Node(trace_node(cx, &mats[c[0]])?));
    }
    Some(V::List(out))
}

fn representation_decompose(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [g, m] = a else { return None };
    let (_, _, ct) = table_of(cx, *g)?;
    let mats = matrices(cx.graph, *m)?;
    if mats.len() != ct.n {
        return None;
    }
    let bindings = HashMap::new();
    let mut chi = Vec::new();
    for &r in &ct.reps {
        let tr = trace_node(cx, &mats[r])?;
        chi.push(cx.graph.eval_complex(tr, &bindings)?);
    }
    Some(V::ints(ct.decompose(&chi)?))
}

fn character_projection(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [g, i, m] = a else { return None };
    let (_, _, ct) = table_of(cx, *g)?;
    let i = idx(cx.graph, *i)?.checked_sub(1).filter(|&i| i < ct.rows.len())?;
    let mats = matrices(cx.graph, *m)?;
    if mats.len() != ct.n {
        return None;
    }
    let dim = mats[0].len();
    if mats.iter().any(|m| m.len() != dim || m.iter().any(|r| r.len() != dim)) {
        return None;
    }
    let coeffs: Vec<NodeId> = (0..ct.n)
        .map(|x| {
            let conj = ct.rows[i][ct.class_of[x]].conj();
            entry_node(cx.graph, &conj)
        })
        .collect();
    let scale = rat_node(cx.graph, i64::try_from(ct.degrees[i]).ok()?, i64::try_from(ct.n).ok()?);
    let mut out = Vec::new();
    for r in 0..dim {
        let mut row = Vec::new();
        for c in 0..dim {
            let terms: Vec<NodeId> = (0..ct.n).map(|x| prod(cx.graph, &[coeffs[x], mats[x][r][c]])).collect();
            let s = sum(cx.graph, &terms);
            let scaled = prod(cx.graph, &[scale, s]);
            row.push(V::Node(cx.simplify(scaled)));
        }
        out.push(V::List(row));
    }
    Some(V::List(out))
}

pub(crate) fn install(i: &mut Installer<'_>) -> Result<(), RuleError> {
    def(i, "group_class_count", Arity::Fixed(1), group_class_count)?;
    def(i, "group_class_sizes", Arity::Fixed(1), group_class_sizes)?;
    def(i, "group_class_representatives", Arity::Fixed(1), group_class_representatives)?;
    def(i, "group_class_index", Arity::Fixed(2), group_class_index)?;
    def(i, "group_character_table", Arity::Fixed(1), group_character_table)?;
    def(i, "group_character_degrees", Arity::Fixed(1), group_character_degrees)?;
    def(i, "character_table_is_orthogonal", Arity::Fixed(1), character_table_is_orthogonal)?;
    def(i, "character_inner_product", Arity::Fixed(3), character_inner_product)?;
    def(i, "character_is_irreducible", Arity::Fixed(2), character_is_irreducible)?;
    def(i, "character_decompose", Arity::Fixed(2), character_decompose)?;
    def(i, "character_tensor", Arity::Fixed(3), character_tensor)?;
    def(i, "character_sym_square", Arity::Fixed(2), character_sym_square)?;
    def(i, "character_alt_square", Arity::Fixed(2), character_alt_square)?;
    def(i, "character_adams", Arity::Fixed(3), character_adams)?;
    def(i, "character_conjugate", Arity::Fixed(2), character_conjugate)?;
    def(i, "character_regular", Arity::Fixed(1), character_regular)?;
    def(i, "character_of_matrices", Arity::Fixed(2), character_of_matrices)?;
    def(i, "representation_decompose", Arity::Fixed(2), representation_decompose)?;
    def(i, "character_projection", Arity::Fixed(3), character_projection)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use num_complex::Complex64;

    use super::super::test_util::num_rows;
    use super::super::test_util::s;

    fn c(re: f64) -> Complex64 {
        Complex64::new(re, 0.0)
    }

    /// Whether `table` contains `row` (up to the tolerance).
    fn has_row(
        table: &[Vec<Complex64>],
        row: &[Complex64],
    ) -> bool {
        table.iter().any(|r| r.len() == row.len() && r.iter().zip(row).all(|(a, b)| (a - b).norm() < 1e-9))
    }

    fn rows_of(
        expected: &[&[f64]],
        table: &[Vec<Complex64>],
    ) {
        assert_eq!(table.len(), expected.len(), "{table:?}");
        for e in expected {
            let row: Vec<Complex64> = e.iter().map(|&x| c(x)).collect();
            assert!(has_row(table, &row), "missing {e:?} in {table:?}");
        }
    }

    #[test]
    fn s3_table() {
        // classes: identity, transpositions, 3-cycles
        let t = num_rows("group_character_table(symmetric_group(3))");
        rows_of(&[&[1.0, 1.0, 1.0], &[1.0, -1.0, 1.0], &[2.0, 0.0, -1.0]], &t);
        assert_eq!(s("group_character_table(symmetric_group(3))"), "list(list(1, 1, 1), list(1, -1, 1), list(2, 0, -1))");
        assert_eq!(s("group_character_degrees(symmetric_group(3))"), "list(1, 1, 2)");
        assert_eq!(s("group_class_sizes(symmetric_group(3))"), "list(1, 3, 2)");
        assert_eq!(s("group_class_count(symmetric_group(3))"), "3");
        assert_eq!(s("group_class_index(symmetric_group(3), list(2, 3, 1))"), "3");
        assert_eq!(s("character_table_is_orthogonal(symmetric_group(3))"), "true");
    }

    #[test]
    fn d4_table() {
        // classes: r0, {r1,r3}, r2, {s0,s2}, {s1,s3}
        let t = num_rows("group_character_table(dihedral_group(4))");
        rows_of(
            &[
                &[1.0, 1.0, 1.0, 1.0, 1.0],
                &[1.0, 1.0, 1.0, -1.0, -1.0],
                &[1.0, -1.0, 1.0, 1.0, -1.0],
                &[1.0, -1.0, 1.0, -1.0, 1.0],
                &[2.0, 0.0, -2.0, 0.0, 0.0],
            ],
            &t,
        );
    }

    const Q8: &str = "fp_group(list(a, b), list(list(a^4), list(a, a, -2, -2), list(b, a, -2, a)))";

    #[test]
    fn q8_table() {
        assert_eq!(s(&format!("group_order({Q8})")), "8");
        assert_eq!(s(&format!("group_class_count({Q8})")), "5");
        assert_eq!(s(&format!("group_character_degrees({Q8})")), "list(1, 1, 1, 1, 2)");
        let t = num_rows(&format!("group_character_table({Q8})"));
        // the two-dimensional character is 2 on the identity, -2 on the
        // centre and 0 on the three classes of elements of order 4
        let two = &t[4];
        assert!((two[0] - c(2.0)).norm() < 1e-9);
        let centre = two.iter().position(|z| (z - c(-2.0)).norm() < 1e-9).unwrap_or(0);
        assert!(centre > 0);
        assert_eq!(two.iter().filter(|z| z.norm() < 1e-9).count(), 3);
        // the four linear characters are trivial on the centre
        for row in &t[..4] {
            assert!((row[centre] - c(1.0)).norm() < 1e-9);
        }
        // D4 and Q8 have the same character table but are not isomorphic
        assert_eq!(s(&format!("group_is_isomorphic({Q8}, dihedral_group(4))")), "false");
    }

    #[test]
    fn a4_table_has_cube_roots_of_unity() {
        let a4 = "group_from_perms(list(list(2,3,1,4), list(1,3,4,2)))";
        assert_eq!(s(&format!("group_order({a4})")), "12");
        assert_eq!(s(&format!("group_character_degrees({a4})")), "list(1, 1, 1, 3)");
        let t = num_rows(&format!("group_character_table({a4})"));
        let w = Complex64::from_polar(1.0, 2.0 * std::f64::consts::PI / 3.0);
        // classes: identity, two classes of 3-cycles, double transpositions
        assert_eq!(s(&format!("group_class_sizes({a4})")), "list(1, 4, 4, 3)");
        let complex_rows: Vec<&Vec<Complex64>> = t.iter().filter(|r| r.iter().any(|z| z.im.abs() > 1e-9)).collect();
        assert_eq!(complex_rows.len(), 2);
        for r in complex_rows {
            assert!((r[0] - c(1.0)).norm() < 1e-9 && (r[3] - c(1.0)).norm() < 1e-9);
            let (x, y) = (r[1], r[2]);
            assert!(((x - w).norm() < 1e-9 && (y - w.conj()).norm() < 1e-9) || ((x - w.conj()).norm() < 1e-9 && (y - w).norm() < 1e-9));
        }
        rows_of(&[&[3.0, 0.0, 0.0, -1.0]], &t[3..]);
        // the entries are written with exponentials
        let text = s(&format!("group_character_table({a4})"));
        assert!(text.contains("exp("), "{text}");
    }

    #[test]
    fn s4_table() {
        let t = num_rows("group_character_table(symmetric_group(4))");
        assert_eq!(t.len(), 5);
        let deg: Vec<f64> = t.iter().map(|r| r[0].re).collect();
        assert_eq!(deg, vec![1.0, 1.0, 2.0, 3.0, 3.0]);
        assert_eq!(s("character_table_is_orthogonal(symmetric_group(4))"), "true");
        // classes: identity, transpositions, 3-cycles, double transpositions, 4-cycles
        assert_eq!(s("group_class_sizes(symmetric_group(4))"), "list(1, 6, 8, 3, 6)");
        // the standard representation (3, 1, -1, 0, -1) is a row
        rows_of(&[&[3.0, 1.0, 0.0, -1.0, -1.0], &[3.0, -1.0, 0.0, -1.0, 1.0], &[2.0, 0.0, -1.0, 2.0, 0.0]], &t[2..]);
    }

    #[test]
    fn a5_table_has_the_golden_ratio() {
        let a5 = "group_from_perms(list(list(2,3,4,5,1), list(2,3,1,4,5)))";
        assert_eq!(s(&format!("group_class_count({a5})")), "5");
        assert_eq!(s(&format!("group_character_degrees({a5})")), "list(1, 3, 3, 4, 5)");
        let t = num_rows(&format!("group_character_table({a5})"));
        let phi = (1.0 + 5.0_f64.sqrt()) / 2.0;
        let psi = (1.0 - 5.0_f64.sqrt()) / 2.0;
        let sizes = s(&format!("group_class_sizes({a5})"));
        assert_eq!(sizes, "list(1, 20, 15, 12, 12)");
        rows_of(&[&[3.0, 0.0, -1.0, phi, psi], &[3.0, 0.0, -1.0, psi, phi], &[4.0, 1.0, 0.0, -1.0, -1.0], &[5.0, -1.0, 1.0, 0.0, 0.0]], &t[1..]);
        let text = s(&format!("group_character_table({a5})"));
        assert!(text.contains("sqrt(5)"), "{text}");
        assert_eq!(s(&format!("character_table_is_orthogonal({a5})")), "true");
    }

    #[test]
    fn cyclic_group_table() {
        let t = num_rows("group_character_table(cyclic_group(5))");
        assert_eq!(t.len(), 5);
        for (a, ra) in t.iter().enumerate() {
            for (b, rb) in t.iter().enumerate() {
                let ip: Complex64 = ra.iter().zip(rb).map(|(x, y)| x * y.conj()).sum::<Complex64>() / 5.0;
                assert!((ip - c(if a == b { 1.0 } else { 0.0 })).norm() < 1e-9);
            }
        }
        assert_eq!(s("group_character_table(cyclic_group(2))"), "list(list(1, 1), list(1, -1))");
    }

    #[test]
    fn decomposition_and_products() {
        let g = "symmetric_group(3)";
        // the regular representation contains each irreducible d times
        assert_eq!(s(&format!("character_decompose({g}, character_regular({g}))")), "list(1, 1, 2)");
        // the permutation representation on three points: 1 + 2
        assert_eq!(s(&format!("character_decompose({g}, list(3, 1, 0))")), "list(1, 0, 1)");
        // 2 x 2 = 1 + sign + 2
        assert_eq!(s(&format!("character_tensor({g}, list(2, 0, -1), list(2, 0, -1))")), "list(4, 0, 1)");
        assert_eq!(s(&format!("character_decompose({g}, character_tensor({g}, list(2, 0, -1), list(2, 0, -1)))")), "list(1, 1, 1)");
        // Sym^2 of the standard representation is 1 + 2, Alt^2 is the sign
        assert_eq!(s(&format!("character_decompose({g}, character_sym_square({g}, list(2, 0, -1)))")), "list(1, 0, 1)");
        assert_eq!(s(&format!("character_decompose({g}, character_alt_square({g}, list(2, 0, -1)))")), "list(0, 1, 0)");
        assert_eq!(s(&format!("character_alt_square({g}, list(2, 0, -1))")), "list(1, -1, 1)");
        assert_eq!(s(&format!("character_is_irreducible({g}, list(2, 0, -1))")), "true");
        assert_eq!(s(&format!("character_is_irreducible({g}, list(3, 1, 0))")), "false");
        assert_eq!(s(&format!("character_inner_product({g}, list(3, 1, 0), list(3, 1, 0))")), "2");
        assert_eq!(s(&format!("character_inner_product({g}, list(1, 1, 1), list(1, -1, 1))")), "0");
        assert_eq!(s(&format!("character_inner_product({g}, list(1, 1, 1), list(1, 1, 0))")), "2/3");
        assert_eq!(s(&format!("character_adams({g}, list(2, 0, -1), 2)")), "list(2, 2, -1)");
        // not a character: stays unreduced
        assert!(s(&format!("character_decompose({g}, list(1, 0, 0))")).starts_with("character_decompose(group("));
    }

    #[test]
    fn matrix_representations() {
        // the defining permutation representation of S3 on R^3
        let perms = ["list(1,2,3)", "list(1,3,2)", "list(2,1,3)", "list(2,3,1)", "list(3,1,2)", "list(3,2,1)"];
        let mat = |p: &str| -> String {
            let img: Vec<usize> = p[5..p.len() - 1].split(',').map(|x| x.trim().parse::<usize>().unwrap_or(1)).collect();
            let rows: Vec<String> = (0..3)
                .map(|i| {
                    let r: Vec<String> = (0..3).map(|j| if img[j] == i + 1 { "1".into() } else { "0".into() }).collect();
                    format!("list({})", r.join(", "))
                })
                .collect();
            format!("list({})", rows.join(", "))
        };
        let reps = format!("list({})", perms.iter().map(|p| mat(p)).collect::<Vec<_>>().join(", "));
        let g = "symmetric_group(3)";
        assert_eq!(s(&format!("character_of_matrices({g}, {reps})")), "list(3, 1, 0)");
        assert_eq!(s(&format!("representation_decompose({g}, {reps})")), "list(1, 0, 1)");
        // projection onto the trivial isotypic component averages the matrices
        assert_eq!(
            s(&format!("character_projection({g}, 1, {reps})")),
            "list(list(1/3, 1/3, 1/3), list(1/3, 1/3, 1/3), list(1/3, 1/3, 1/3))"
        );
        // the projections onto all isotypic components add up to the identity
        let p1 = s(&format!("character_projection({g}, 1, {reps})"));
        let p3 = s(&format!("character_projection({g}, 3, {reps})"));
        assert_eq!(p1.matches("1/3").count(), 9);
        assert!(p3.contains("2/3"), "{p3}");
        assert_eq!(s(&format!("character_projection({g}, 2, {reps})")), "list(list(0, 0, 0), list(0, 0, 0), list(0, 0, 0))");
    }
}
