//! Algebraic topology: simplicial complexes, homology and persistence.
//!
//! A simplicial complex is the inert term `sc(list(simplex, ...))`: each
//! simplex is a sorted `list` of vertex integers, the list is closed under
//! faces and sorted by dimension and then lexicographically. Every operator
//! that reads a complex normalises it first, so any list of simplices may be
//! wrapped in `sc(...)` by hand. A *chain* is `list(list(coeff, simplex),
//! ...)`; the coefficients may be arbitrary terms. Point clouds are lists of
//! coordinate lists.
//!
//! The numeric algorithms live in [`crate::kernels::topology`]; Betti numbers
//! use exact rational ranks of the integer boundary matrices.
//!
//! | operator | value |
//! |---|---|
//! | `sc_complex(list(simplices...))` | the complex generated by the simplices (closed under faces, normalised) |
//! | `sc_dimension(K)` | the dimension (`-1` for the empty complex) |
//! | `sc_simplices(K, k)` | the `k`-simplices |
//! | `sc_simplex_dimension(s)` | `len(s) - 1` |
//! | `sc_euler_characteristic(K)` | `sum (-1)^k #k-simplices` |
//! | `sc_boundary(s)` | the boundary chain `list(list(coeff, face), ...)`, signs `(-1)^i` |
//! | `sc_boundary_matrix(K, k)`, `sc_coboundary_matrix(K, k)` | integer matrix of `d_k` (rows `(k-1)`-simplices, columns `k`-simplices) and of `d^k` (its transpose) |
//! | `sc_chain_boundary(K, chain)` | the boundary of a chain of `k`-simplices of `K`; coefficients simplified, zeros dropped |
//! | `sc_betti(K, k)`, `sc_cohomology_betti(K, k)` | Betti numbers (homology, cohomology) |
//! | `sc_verify_boundary(K)`, `sc_verify_coboundary(K)` | `d d = 0` (resp. `d^ d^ = 0`) |
//! | `sc_components(K)` | connected components of the 1-skeleton, as vertex lists |
//! | `sc_grid(w, h)`, `sc_torus(m, n)` | triangulated grid; triangulated torus (`m, n >= 3`) |
//! | `vietoris_rips(points, eps[, max_dim])` | the Vietoris-Rips complex (`max_dim` defaults to 2) |
//! | `vietoris_rips_filtration(points, max_eps, steps)` | `list(list(eps, K), ...)`, the 1-skeleton at `steps + 1` radii |
//! | `betti_at_radius(points, eps, max_dim)` | `list(b0, ..., b_max_dim)` of the Vietoris-Rips complex |
//! | `persistence(points, max_eps, steps, max_dim)` | per dimension the list of `list(birth, death)` (naive algorithm: Betti numbers tracked over `steps + 1` radii) |
//! | `euclidean_distance(p, q)` | the distance of two points (float) |

use super::apply;
use super::def;
use super::def_inert;
use super::float;
use super::floats;
use super::idx;
use super::idxs;
use super::is_zero;
use super::items;
use super::prod;
use super::sum;
use super::V;
use crate::graph::rule::Installer;
use crate::graph::Arity;
use crate::graph::Cx;
use crate::graph::Graph;
use crate::graph::NodeId;
use crate::graph::RuleError;
use crate::kernels::topology as kt;
use crate::kernels::topology::Simplex;

/// Largest point cloud / `max_dim` / step count accepted.
const MAX_POINTS: usize = 300;
const MAX_DIM: usize = 8;
const MAX_STEPS: usize = 2000;

fn simplex_v(s: &[usize]) -> V {
    V::ints(s.iter().map(|&v| v as u64))
}

fn complex_v(
    g: &mut Graph,
    complex: &[Simplex],
) -> Option<V> {
    let list = V::List(complex.iter().map(|s| simplex_v(s)).collect()).build(g);
    apply(g, "sc", &[list]).map(V::Node)
}

fn simplex(
    g: &Graph,
    n: NodeId,
) -> Option<Simplex> {
    idxs(g, n)
}

fn read_simplices(
    g: &Graph,
    n: NodeId,
) -> Option<Vec<Simplex>> {
    items(g, n)?.into_iter().map(|s| simplex(g, s)).collect()
}

/// The complex of an `sc(...)` term, normalised.
fn read_complex(
    g: &Graph,
    node: NodeId,
) -> Option<Vec<Simplex>> {
    let op = g.ops().lookup("sc")?;
    let found = if g.op(node) == op { node } else { g.enodes(g.find(node)).find(|&e| g.op(e) == op)? };
    let [list] = g.children(found) else { return None };
    Some(kt::close_complex(&read_simplices(g, *list)?))
}

fn read_points(
    g: &Graph,
    n: NodeId,
) -> Option<Vec<Vec<f64>>> {
    let points: Vec<Vec<f64>> = items(g, n)?.into_iter().map(|p| floats(g, p)).collect::<Option<_>>()?;
    (points.len() <= MAX_POINTS).then_some(points)
}

fn count(
    g: &Graph,
    n: NodeId,
    limit: usize,
) -> Option<usize> {
    idx(g, n).filter(|&v| v <= limit)
}

fn radius(
    g: &Graph,
    n: NodeId,
) -> Option<f64> {
    float(g, n).filter(|x| x.is_finite() && *x >= 0.0)
}

fn complex_arg(
    cx: &Cx<'_>,
    a: &[NodeId],
) -> Option<Vec<Simplex>> {
    read_complex(cx.graph, *a.first()?)
}

// ----------------------------------------------------------------------
// Complexes and chains
// ----------------------------------------------------------------------

fn sc_complex(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let simplices = read_simplices(cx.graph, *a.first()?)?;
    complex_v(cx.graph, &kt::close_complex(&simplices))
}

fn sc_dimension(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let k = complex_arg(cx, a)?;
    Some(V::int(kt::complex_dimension(&k).map_or(-1, |d| d as i64)))
}

fn sc_simplices(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [k, d] = a else { return None };
    let k = read_complex(cx.graph, *k)?;
    let d = idx(cx.graph, *d)?;
    Some(V::List(kt::simplices_of_dim(&k, d).iter().map(|s| simplex_v(s)).collect()))
}

fn sc_simplex_dimension(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let s = simplex(cx.graph, *a.first()?)?;
    (!s.is_empty()).then(|| V::uint(s.len() - 1))
}

fn sc_euler_characteristic(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    Some(V::int(kt::euler_characteristic(&complex_arg(cx, a)?)))
}

fn sc_boundary(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let s = simplex(cx.graph, *a.first()?)?;
    let mut sorted = s.clone();
    sorted.sort_unstable();
    sorted.dedup();
    if s.is_empty() || sorted.len() != s.len() {
        return None;
    }
    Some(V::List(
        kt::simplex_boundary(&s).into_iter().map(|(c, f)| V::List(vec![V::int(c), simplex_v(&f)])).collect(),
    ))
}

/// The `k`-th boundary matrix of a complex, for `1 <= k <= dim`.
fn boundary_of(
    complex: &[Simplex],
    k: usize,
) -> Option<Vec<Vec<i64>>> {
    if k == 0 {
        return None;
    }
    let cols = kt::simplices_of_dim(complex, k);
    if cols.is_empty() {
        return None;
    }
    Some(kt::boundary_matrix(&kt::simplices_of_dim(complex, k - 1), &cols))
}

fn int_matrix_v(m: &[Vec<i64>]) -> V {
    V::List(m.iter().map(|r| V::ints(r.iter().copied())).collect())
}

fn sc_boundary_matrix(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [k, d] = a else { return None };
    let complex = read_complex(cx.graph, *k)?;
    Some(int_matrix_v(&boundary_of(&complex, idx(cx.graph, *d)?)?))
}

fn sc_coboundary_matrix(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [k, d] = a else { return None };
    let complex = read_complex(cx.graph, *k)?;
    let d = idx(cx.graph, *d)?;
    let m = boundary_of(&complex, d + 1)?;
    let cols = kt::simplices_of_dim(&complex, d + 1).len();
    Some(int_matrix_v(&kt::transpose(&m, cols)))
}

fn sc_chain_boundary(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [k, chain] = a else { return None };
    let complex = read_complex(cx.graph, *k)?;
    let mut terms: Vec<(NodeId, Simplex)> = Vec::new();
    for t in items(cx.graph, *chain)? {
        let [c, s] = items(cx.graph, t)?.as_slice().try_into().ok()?;
        terms.push((c, simplex(cx.graph, s)?));
    }
    let Some((_, first)) = terms.first() else { return Some(V::List(Vec::new())) };
    let dim = first.len().checked_sub(1)?;
    let top = kt::simplices_of_dim(&complex, dim);
    if terms.iter().any(|(_, s)| s.len() != dim + 1 || !top.contains(s)) {
        return None;
    }
    if dim == 0 {
        return Some(V::List(Vec::new()));
    }
    let faces = kt::simplices_of_dim(&complex, dim - 1);
    let mut out = Vec::new();
    for face in &faces {
        let mut parts = Vec::new();
        for (c, s) in &terms {
            for (sign, f) in kt::simplex_boundary(s) {
                if &f == face {
                    let sign = cx.graph.int(sign);
                    parts.push(prod(cx.graph, &[sign, *c]));
                }
            }
        }
        if parts.is_empty() {
            continue;
        }
        let total = sum(cx.graph, &parts);
        let total = cx.simplify(total);
        if !is_zero(cx.graph, total) {
            out.push(V::List(vec![V::Node(total), simplex_v(face)]));
        }
    }
    Some(V::List(out))
}

fn sc_betti(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [k, d] = a else { return None };
    let complex = read_complex(cx.graph, *k)?;
    Some(V::uint(kt::betti_number(&complex, idx(cx.graph, *d)?)))
}

fn sc_cohomology_betti(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [k, d] = a else { return None };
    let complex = read_complex(cx.graph, *k)?;
    Some(V::uint(kt::cohomology_betti_number(&complex, idx(cx.graph, *d)?)))
}

fn sc_verify_boundary(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    Some(V::Bool(kt::verify_boundary_property(&complex_arg(cx, a)?)))
}

fn sc_verify_coboundary(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    Some(V::Bool(kt::verify_coboundary_property(&complex_arg(cx, a)?)))
}

fn sc_components(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let complex = complex_arg(cx, a)?;
    let vertices: Vec<usize> = kt::simplices_of_dim(&complex, 0).into_iter().map(|s| s[0]).collect();
    let pos = |v: usize| vertices.binary_search(&v).ok();
    let mut adj = vec![Vec::new(); vertices.len()];
    for e in kt::simplices_of_dim(&complex, 1) {
        let (u, v) = (pos(e[0])?, pos(e[1])?);
        adj[u].push(v);
        adj[v].push(u);
    }
    let comps = kt::find_connected_components(&adj);
    Some(V::List(
        comps
            .into_iter()
            .map(|c| {
                let mut c: Vec<usize> = c.into_iter().map(|i| vertices[i]).collect();
                c.sort_unstable();
                simplex_v(&c)
            })
            .collect(),
    ))
}

fn sc_grid(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [w, h] = a else { return None };
    let (w, h) = (count(cx.graph, *w, 200)?, count(cx.graph, *h, 200)?);
    complex_v(cx.graph, &kt::grid_complex(w, h))
}

fn sc_torus(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [m, n] = a else { return None };
    let (m, n) = (count(cx.graph, *m, 200)?, count(cx.graph, *n, 200)?);
    if m < 3 || n < 3 {
        return None;
    }
    complex_v(cx.graph, &kt::torus_complex(m, n))
}

// ----------------------------------------------------------------------
// Point clouds
// ----------------------------------------------------------------------

fn vietoris_rips(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let (points, eps, max_dim) = match a {
        | [p, e] => (p, e, 2),
        | [p, e, d] => (p, e, count(cx.graph, *d, MAX_DIM)?),
        | _ => return None,
    };
    let points = read_points(cx.graph, *points)?;
    let eps = radius(cx.graph, *eps)?;
    complex_v(cx.graph, &kt::close_complex(&kt::vietoris_rips_complex(&points, eps, max_dim)))
}

fn vietoris_rips_filtration(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [p, e, s] = a else { return None };
    let points = read_points(cx.graph, *p)?;
    let (eps, steps) = (radius(cx.graph, *e)?, count(cx.graph, *s, MAX_STEPS)?);
    let mut out = Vec::new();
    for (eps, complex) in kt::vietoris_rips_filtration(&points, eps, steps) {
        out.push(V::List(vec![V::Float(eps), complex_v(cx.graph, &complex)?]));
    }
    Some(V::List(out))
}

fn betti_at_radius(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [p, e, d] = a else { return None };
    let points = read_points(cx.graph, *p)?;
    let (eps, dim) = (radius(cx.graph, *e)?, count(cx.graph, *d, MAX_DIM)?);
    Some(V::List(kt::betti_numbers_at_radius(&points, eps, dim).into_iter().map(V::uint).collect()))
}

fn persistence(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [p, e, s, d] = a else { return None };
    let points = read_points(cx.graph, *p)?;
    let eps = radius(cx.graph, *e)?;
    let (steps, dim) = (count(cx.graph, *s, MAX_STEPS)?, count(cx.graph, *d, MAX_DIM)?);
    let diagrams = kt::compute_persistence(&points, eps, steps, dim);
    Some(V::List(
        diagrams
            .into_iter()
            .map(|d| V::List(d.intervals.iter().map(|i| V::List(vec![V::Float(i.birth), V::Float(i.death)])).collect()))
            .collect(),
    ))
}

fn euclidean_distance(
    cx: &mut Cx<'_>,
    a: &[NodeId],
) -> Option<V> {
    let [p, q] = a else { return None };
    let (p, q) = (floats(cx.graph, *p)?, floats(cx.graph, *q)?);
    (p.len() == q.len()).then(|| V::Float(kt::euclidean_distance(&p, &q)))
}

pub(crate) fn install(i: &mut Installer<'_>) -> Result<(), RuleError> {
    def_inert(i, "sc", Arity::Fixed(1))?;
    def(i, "sc_complex", Arity::Fixed(1), sc_complex)?;
    def(i, "sc_dimension", Arity::Fixed(1), sc_dimension)?;
    def(i, "sc_simplices", Arity::Fixed(2), sc_simplices)?;
    def(i, "sc_simplex_dimension", Arity::Fixed(1), sc_simplex_dimension)?;
    def(i, "sc_euler_characteristic", Arity::Fixed(1), sc_euler_characteristic)?;
    def(i, "sc_boundary", Arity::Fixed(1), sc_boundary)?;
    def(i, "sc_boundary_matrix", Arity::Fixed(2), sc_boundary_matrix)?;
    def(i, "sc_coboundary_matrix", Arity::Fixed(2), sc_coboundary_matrix)?;
    def(i, "sc_chain_boundary", Arity::Fixed(2), sc_chain_boundary)?;
    def(i, "sc_betti", Arity::Fixed(2), sc_betti)?;
    def(i, "sc_cohomology_betti", Arity::Fixed(2), sc_cohomology_betti)?;
    def(i, "sc_verify_boundary", Arity::Fixed(1), sc_verify_boundary)?;
    def(i, "sc_verify_coboundary", Arity::Fixed(1), sc_verify_coboundary)?;
    def(i, "sc_components", Arity::Fixed(1), sc_components)?;
    def(i, "sc_grid", Arity::Fixed(2), sc_grid)?;
    def(i, "sc_torus", Arity::Fixed(2), sc_torus)?;
    def(i, "vietoris_rips", Arity::Variadic, vietoris_rips)?;
    def(i, "vietoris_rips_filtration", Arity::Fixed(3), vietoris_rips_filtration)?;
    def(i, "betti_at_radius", Arity::Fixed(3), betti_at_radius)?;
    def(i, "persistence", Arity::Fixed(4), persistence)?;
    def(i, "euclidean_distance", Arity::Fixed(2), euclidean_distance)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::super::test_util::s;

    const SQUARE: &str = "list(list(0, 0), list(1, 0), list(1, 1), list(0, 1))";

    #[test]
    fn complexes_are_normalised() {
        assert_eq!(
            s("sc_complex(list(list(2, 0, 1)))"),
            "sc(list(list(0), list(1), list(2), list(0, 1), list(0, 2), list(1, 2), list(0, 1, 2)))"
        );
        assert_eq!(s("sc_complex(list(list(1, 0), list(0, 1), list(3)))"), "sc(list(list(0), list(1), list(3), list(0, 1)))");
        assert_eq!(s("sc_dimension(sc_complex(list(list(0, 1, 2))))"), "2");
        assert_eq!(s("sc_dimension(sc_complex(list()))"), "-1");
        assert_eq!(s("sc_simplices(sc_complex(list(list(0, 1, 2))), 1)"), "list(list(0, 1), list(0, 2), list(1, 2))");
        assert_eq!(s("sc_simplices(sc_complex(list(list(0, 1))), 5)"), "list()");
        assert_eq!(s("sc_simplex_dimension(list(4, 7, 9))"), "2");
        assert_eq!(s("sc_euler_characteristic(sc_complex(list(list(0, 1, 2))))"), "1");
        assert_eq!(s("sc_euler_characteristic(sc_torus(3, 3))"), "0");
        assert_eq!(s("sc_components(sc_complex(list(list(0, 1), list(2, 3), list(5))))"), "list(list(0, 1), list(2, 3), list(5))");
    }

    #[test]
    fn boundaries() {
        assert_eq!(s("sc_boundary(list(0, 1, 2))"), "list(list(1, list(1, 2)), list(-1, list(0, 2)), list(1, list(0, 1)))");
        assert_eq!(s("sc_boundary(list(3))"), "list()");
        assert_eq!(s("sc_boundary(list(1, 1))"), "sc_boundary(list(1, 1))");
        assert_eq!(
            s("sc_boundary_matrix(sc_complex(list(list(0, 1, 2))), 1)"),
            "list(list(-1, -1, 0), list(1, 0, -1), list(0, 1, 1))"
        );
        assert_eq!(
            s("sc_boundary_matrix(sc_complex(list(list(0, 1, 2))), 2)"),
            "list(list(1), list(-1), list(1))"
        );
        assert_eq!(
            s("sc_coboundary_matrix(sc_complex(list(list(0, 1, 2))), 1)"),
            "list(list(1, -1, 1))"
        );
        assert_eq!(s("sc_boundary_matrix(sc_complex(list(list(0, 1))), 0)"), "sc_boundary_matrix(sc(list(list(0), list(1), list(0, 1))), 0)");
        // chains with symbolic coefficients
        assert_eq!(
            s("sc_chain_boundary(sc_complex(list(list(0, 1, 2))), list(list(a, list(0, 1, 2))))"),
            "list(list(a, list(0, 1)), list(-a, list(0, 2)), list(a, list(1, 2)))"
        );
        // the boundary of a boundary vanishes
        assert_eq!(
            s("sc_chain_boundary(sc_complex(list(list(0, 1, 2))), list(list(1, list(0, 1)), list(1, list(1, 2)), list(-1, list(0, 2))))"),
            "list()"
        );
        assert_eq!(
            s("sc_chain_boundary(sc_complex(list(list(0, 1, 2))), list(list(x, list(0, 1)), list(y, list(1, 2))))"),
            "list(list(-x, list(0)), list(x - y, list(1)), list(y, list(2)))"
        );
        assert_eq!(s("sc_chain_boundary(sc_complex(list(list(0, 1))), list(list(1, list(0))))"), "list()");
        assert!(s("sc_chain_boundary(sc_complex(list(list(0, 1))), list(list(1, list(0, 2))))").starts_with("sc_chain_boundary(sc("));
    }

    #[test]
    fn homology() {
        let hollow = "sc_complex(list(list(0, 1), list(1, 2), list(0, 2)))";
        let filled = "sc_complex(list(list(0, 1, 2)))";
        assert_eq!(s(&format!("sc_betti({hollow}, 0)")), "1");
        assert_eq!(s(&format!("sc_betti({hollow}, 1)")), "1");
        assert_eq!(s(&format!("sc_betti({filled}, 1)")), "0");
        assert_eq!(s(&format!("sc_cohomology_betti({hollow}, 1)")), "1");
        assert_eq!(s(&format!("sc_cohomology_betti({filled}, 0)")), "1");
        assert_eq!(s("sc_betti(sc_complex(list(list(0), list(1))), 0)"), "2");
        assert_eq!(s("sc_betti(sc_torus(3, 3), 0)"), "1");
        assert_eq!(s("sc_betti(sc_torus(3, 3), 1)"), "2");
        assert_eq!(s("sc_betti(sc_torus(3, 3), 2)"), "1");
        assert_eq!(s("sc_cohomology_betti(sc_torus(3, 3), 1)"), "2");
        assert_eq!(s("sc_betti(sc_torus(3, 3), 3)"), "0");
        assert_eq!(s("sc_betti(sc_grid(2, 2), 1)"), "0");
        assert_eq!(s("sc_verify_boundary(sc_torus(3, 4))"), "true");
        assert_eq!(s("sc_verify_coboundary(sc_torus(3, 4))"), "true");
        assert_eq!(s("sc_verify_boundary(sc_grid(3, 2))"), "true");
        assert_eq!(s("sc_dimension(sc_grid(3, 2))"), "2");
        assert_eq!(s("sc_torus(2, 3)"), "sc_torus(2, 3)");
    }

    #[test]
    fn point_clouds() {
        assert_eq!(s(&format!("betti_at_radius({SQUARE}, 1.1, 1)")), "list(1, 1)");
        assert_eq!(s(&format!("betti_at_radius({SQUARE}, 1.5, 3)")), "list(1, 0, 0, 0)");
        assert_eq!(s(&format!("sc_betti(vietoris_rips({SQUARE}, 1.1), 1)")), "1");
        assert_eq!(s(&format!("sc_betti(vietoris_rips({SQUARE}, 1.5, 3), 1)")), "0");
        assert_eq!(s(&format!("sc_dimension(vietoris_rips({SQUARE}, 1.5, 3))")), "3");
        assert_eq!(s(&format!("sc_dimension(vietoris_rips({SQUARE}, 0.5, 3))")), "0");
        assert_eq!(s("euclidean_distance(list(0, 0), list(3, 4))"), "5");
        let filtration = s(&format!("vietoris_rips_filtration({SQUARE}, 2, 2)"));
        assert!(filtration.starts_with("list(list(0, sc(list(list(0), list(1), list(2), list(3)))), list(1, sc("), "{filtration}");
        let d = s(&format!("persistence({SQUARE}, 1.5, 3, 2)"));
        assert!(d.starts_with("list(list(list("), "{d}");
        assert_eq!(d.matches("list(").count(), 10, "{d}");
    }
}
