//! Conservation laws by the multiplier method.
//!
//! A local conservation law `D_t T + D_x X = 0` of `Δ = 0` is generated by
//! a multiplier `Λ` with `Λ Δ = D_t T + D_x X` identically. A function is
//! a total divergence exactly when the Euler operator
//! `E_u(F) = Σ_J (-D)_J ∂F/∂u_J` annihilates it, so the multipliers are the
//! solutions of the linear identity `E_u(Λ Δ) = 0`. Multipliers are sought
//! as polynomials of degree ≤ 2 in `x`, `t`, `u`, plus terms linear in
//! `u_x` and `u_xx` (which give the energy-type laws of KdV-type
//! equations).
//!
//! For an evolution equation `u_t = G` and a multiplier `Λ(x, t, u)` the
//! density is `T = ∫ Λ du` and the flux is `X = D_x⁻¹(-Λ G - T_t)`,
//! inverted with the one-dimensional homotopy operator
//! `D_x⁻¹ R = ∫₀¹ Σ_k Σ_{j<k} u_j (-D_x)^(k-1-j) ∂R/∂u_k |_{λu} dλ/λ +
//! ∫ R|_{u=0} dx` and checked by differentiation.

use super::Problem;
use super::symmetry::Jets;
use super::symmetry::to_jets;
use crate::graph::Cx;
use crate::graph::NodeId;
use crate::graph::Number;
use crate::graph::op::core;
use crate::rules::calculus::antiderivative;
use crate::rules::calculus::derivative;
use crate::rules::complex::build::add;
use crate::rules::complex::build::mul;
use crate::rules::complex::build::sub;

/// `E_u(F)`.
fn euler_operator(
    cx: &mut Cx<'_>,
    jets: &mut Jets,
    f: NodeId,
) -> Option<NodeId> {
    let mut terms = Vec::new();
    for (index, node) in jets.occurring(cx, f) {
        let partial = derivative(cx.graph, f, node)?;
        let partial = cx.simplify(partial);
        if cx.is_zero(partial) {
            continue;
        }
        let d = jets.total_multi(cx, partial, &index)?;
        let order: u32 = index.iter().sum();
        let sign = cx.graph.int(if order % 2 == 0 { 1 } else { -1 });
        terms.push(mul(cx.graph, &[sign, d]));
    }
    let sum = add(cx.graph, &terms);
    Some(cx.simplify(sum))
}

/// `∫₀¹ e dλ` for an expression polynomial (or at least integrable) in λ.
fn integrate_unit(
    cx: &mut Cx<'_>,
    e: NodeId,
    lambda: NodeId,
) -> Option<NodeId> {
    let primitive = antiderivative(cx, e, lambda)?;
    let one = cx.graph.int(1);
    let zero = cx.graph.int(0);
    let upper = cx.graph.substitute(primitive, lambda, one);
    let lower = cx.graph.substitute(primitive, lambda, zero);
    let difference = sub(cx.graph, upper, lower);
    Some(cx.simplify(difference))
}

/// `D_x⁻¹ R` by the homotopy operator, verified.
fn invert_dx(
    cx: &mut Cx<'_>,
    jets: &mut Jets,
    r: NodeId,
    x_index: usize,
) -> Option<NodeId> {
    let n = jets.vars.len();
    let pure_x = |i: &Vec<u32>| i.iter().enumerate().all(|(k, &e)| k == x_index || e == 0);
    let present = jets.occurring(cx, r);
    if present.iter().any(|(i, _)| !pure_x(i)) {
        return None;
    }
    let max_k = present.iter().map(|(i, _)| i[x_index]).max().unwrap_or(0);
    let jet_k = |cx: &mut Cx<'_>, jets: &mut Jets, k: u32| {
        let mut index = vec![0; n];
        index[x_index] = k;
        jets.get(cx, &index)
    };
    let mut terms = Vec::new();
    for k in 1..=max_k {
        let uk = jet_k(cx, jets, k);
        let partial = derivative(cx.graph, r, uk)?;
        let partial = cx.simplify(partial);
        if cx.is_zero(partial) {
            continue;
        }
        for j in 0..k {
            let uj = jet_k(cx, jets, j);
            // (-D_x)^(k-1-j) ∂R/∂u_k
            let mut d = partial;
            for _ in 0..(k - 1 - j) {
                d = jets.total(cx, d, x_index)?;
                let minus = cx.graph.int(-1);
                d = mul(cx.graph, &[minus, d]);
            }
            terms.push(mul(cx.graph, &[uj, d]));
        }
    }
    let integrand = add(cx.graph, &terms);
    let lambda_symbol = cx.graph.interner_mut().fresh_symbol("lambda");
    let lambda = cx.graph.symbol_node(lambda_symbol);
    let mut scaled = integrand;
    let mut at_zero = r;
    let zero = cx.graph.int(0);
    for (_, node) in jets.occurring(cx, integrand) {
        let s = mul(cx.graph, &[lambda, node]);
        scaled = cx.graph.substitute(scaled, node, s);
    }
    for (_, node) in jets.occurring(cx, r) {
        at_zero = cx.graph.substitute(at_zero, node, zero);
    }
    let minus_one = cx.graph.int(-1);
    let inv_lambda = cx.graph.node(core::POW, &[lambda, minus_one]);
    let scaled = mul(cx.graph, &[scaled, inv_lambda]);
    let scaled = cx.simplify(scaled);
    let homotopy = if cx.is_zero(scaled) { cx.graph.int(0) } else { integrate_unit(cx, scaled, lambda)? };
    let at_zero = cx.simplify(at_zero);
    let x = jets.vars[x_index];
    let base = if cx.is_zero(at_zero) { cx.graph.int(0) } else { antiderivative(cx, at_zero, x)? };
    let flux = add(cx.graph, &[homotopy, base]);
    let flux = cx.simplify(flux);
    // Verify D_x X = R.
    let check = jets.total(cx, flux, x_index)?;
    let residual = sub(cx.graph, check, r);
    cx.is_zero(residual).then_some(flux)
}

/// `list(list(Λ, T, X), …)`; `T` and `X` are omitted (only `list(Λ)`) for
/// multipliers depending on derivatives or for non-evolution equations.
pub(super) fn conservation_laws(
    cx: &mut Cx<'_>,
    p: &Problem,
) -> Option<NodeId> {
    if p.vars.len() != 2 {
        return None;
    }
    let t_index = p.time(cx.graph);
    let x_index = 1 - t_index;
    let (x, t) = (p.vars[x_index], p.vars[t_index]);
    let mut jets = Jets::new(&p.vars);
    let delta = to_jets(cx, p, &mut jets);
    let delta = cx.simplify(delta);
    let n = 2;
    let u0 = jets.get(cx, &vec![0; n]);
    let mut e_x = vec![0; n];
    e_x[x_index] = 1;
    let ux = jets.get(cx, &e_x);
    let mut e_xx = vec![0; n];
    e_xx[x_index] = 2;
    let uxx = jets.get(cx, &e_xx);
    // Ansatz: polynomial of degree ≤ 2 in x, t, u, plus u_x and u_xx.
    let vars = [x, t, u0];
    let mut monomials = vec![cx.graph.int(1)];
    for (i, &a) in vars.iter().enumerate() {
        monomials.push(a);
        for &b in &vars[i..] {
            monomials.push(mul(cx.graph, &[a, b]));
        }
    }
    monomials.push(ux);
    monomials.push(uxx);
    let mut unknowns = Vec::with_capacity(monomials.len());
    let mut terms = Vec::with_capacity(monomials.len());
    for &m in &monomials {
        let s = cx.graph.interner_mut().fresh_symbol("m");
        let c = cx.graph.symbol_node(s);
        unknowns.push(c);
        terms.push(mul(cx.graph, &[c, m]));
    }
    let lambda = add(cx.graph, &terms);
    let product = mul(cx.graph, &[lambda, delta]);
    let euler = euler_operator(cx, &mut jets, product)?;
    let solutions = crate::rules::ode::solve_linear_identity(cx.graph, euler, &unknowns)?;
    // u_t = G for the density and flux.
    let mut e_t = vec![0; n];
    e_t[t_index] = 1;
    let ut = jets.get(cx, &e_t);
    let evolution = crate::rules::ode::coefficients_of(cx.graph, delta, ut).and_then(|parts| match parts.as_slice() {
        | [c0, c1] if cx.graph.number_of(*c1).is_some_and(|v| !v.is_zero()) => {
            let minus = cx.graph.int(-1);
            let inverse = cx.graph.node(core::POW, &[*c1, minus]);
            let g = mul(cx.graph, &[minus, *c0, inverse]);
            let g = cx.simplify(g);
            (!crate::rules::ode::occurs_in(cx.graph, g, ut)).then_some(g)
        },
        | _ => None,
    });
    let mut laws = Vec::new();
    for v in solutions {
        let mut multiplier = lambda;
        for (u, c) in unknowns.iter().zip(&v) {
            let c = cx.graph.num(Number::rat(c.clone()));
            multiplier = cx.graph.substitute(multiplier, *u, c);
        }
        let multiplier = cx.simplify(multiplier);
        if cx.is_zero(multiplier) {
            continue;
        }
        let zeroth = !crate::rules::ode::occurs_in(cx.graph, multiplier, ux)
            && !crate::rules::ode::occurs_in(cx.graph, multiplier, uxx);
        let law = match (evolution, zeroth) {
            | (Some(g), true) => (|| {
                let density = antiderivative(cx, multiplier, u0)?;
                let density = cx.simplify(density);
                let dt = derivative(cx.graph, density, t)?;
                let product = mul(cx.graph, &[multiplier, g]);
                let r = add(cx.graph, &[product, dt]);
                let minus = cx.graph.int(-1);
                let r = mul(cx.graph, &[minus, r]);
                let r = cx.simplify(r);
                let flux = invert_dx(cx, &mut jets, r, x_index)?;
                Some(vec![multiplier, density, flux])
            })()
            .unwrap_or_else(|| vec![multiplier]),
            | _ => vec![multiplier],
        };
        // Back from jets to derivatives of u.
        let restored: Vec<NodeId> = law.into_iter().map(|e| from_jets(cx, p, &jets, e)).collect();
        laws.push(cx.graph.node(core::LIST, &restored));
    }
    Some(cx.graph.node(core::LIST, &laws))
}

/// Replaces jet symbols by `diff` requests of `u`.
fn from_jets(
    cx: &mut Cx<'_>,
    p: &Problem,
    jets: &Jets,
    e: NodeId,
) -> NodeId {
    let Some(diff) = cx.graph.ops().lookup("diff") else {
        return e;
    };
    let mut out = e;
    for (index, node) in jets.occurring(cx, e) {
        let mut d = p.unknown;
        for (k, &times) in index.iter().enumerate() {
            for _ in 0..times {
                d = cx.graph.node(diff, &[d, p.vars[k]]);
            }
        }
        out = cx.graph.substitute(out, node, d);
    }
    cx.simplify(out)
}
