//! # C interface
//!
//! A deliberately small C ABI over [`crate::api`]. Every entry point is
//! `extern "C"`, never unwinds (panics become [`RssnStatus::Panic`]) and
//! reports failures through a status code plus a thread-local message
//! readable with [`rssn_last_error`].
//!
//! Ownership rules:
//! * `rssn_session_new` / `rssn_config_new` return heap objects that must
//!   be released with `rssn_session_free` / `rssn_config_free`.
//! * Terms are `uint32_t` handles valid for the session that made them;
//!   [`RSSN_NO_TERM`] signals failure.
//! * Strings returned by rssn are owned by the caller and must be released
//!   with `rssn_string_free`; tensors with `rssn_tensor_free`.
//!
//! The header `rssn.h` is generated by cbindgen (`DEV=1 cargo build`).

// The C ABI necessarily dereferences raw pointers handed in by the caller.
#![allow(unsafe_code)]

mod compute;
mod term;

use std::cell::RefCell;
use std::ffi::CStr;
use std::ffi::CString;
use std::os::raw::c_char;
use std::panic::AssertUnwindSafe;
use std::panic::catch_unwind;

pub use compute::*;
pub use term::*;

use crate::api::ComputeError;

/// The handle value that means "no term" (a failed constructor).
pub const RSSN_NO_TERM: u32 = u32::MAX;

/// Outcome of an rssn C call.
#[repr(C)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum RssnStatus {
    /// Success.
    Ok = 0,
    /// A required pointer argument was null.
    NullArgument = 1,
    /// A string argument was not valid UTF-8.
    InvalidUtf8 = 2,
    /// Input text could not be parsed.
    Parse = 3,
    /// An operator name is not registered, or got the wrong arity.
    UnknownOperator = 4,
    /// A numeric answer was requested but none could be determined.
    NotNumeric = 5,
    /// A rule set derived a contradiction; discard the session.
    Inconsistent = 6,
    /// A rule set failed to install.
    Rule = 7,
    /// A term handle does not belong to the session.
    NoSuchTerm = 8,
    /// The term has no value of the requested kind.
    NoValue = 9,
    /// A simulation failed or was given bad parameters.
    Simulation = 10,
    /// rssn panicked; this is a bug.
    Panic = 11,
}

thread_local! {
    static LAST_ERROR: RefCell<CString> = RefCell::new(CString::default());
}

fn set_error(message: &str) {
    let text = CString::new(message.replace('\0', " ")).unwrap_or_default();
    LAST_ERROR.with(|e| *e.borrow_mut() = text);
}

/// Records `message` and returns `status`.
pub(crate) fn fail(
    status: RssnStatus,
    message: &str,
) -> RssnStatus {
    set_error(message);
    status
}

pub(crate) fn compute_error(e: &ComputeError) -> RssnStatus {
    let status = match e {
        | ComputeError::Rule(_) => RssnStatus::Rule,
        | ComputeError::Parse(_) => RssnStatus::Parse,
        | ComputeError::UnknownOperator(_) => RssnStatus::UnknownOperator,
        | ComputeError::NotNumeric(_) => RssnStatus::NotNumeric,
        | ComputeError::Inconsistent(_) => RssnStatus::Inconsistent,
    };
    fail(status, &e.to_string())
}

/// Runs `body`, turning a panic into [`RssnStatus::Panic`].
pub(crate) fn guard(body: impl FnOnce() -> RssnStatus) -> RssnStatus {
    catch_unwind(AssertUnwindSafe(body)).unwrap_or_else(|panic| {
        let message = panic
            .downcast_ref::<String>()
            .map(String::as_str)
            .or_else(|| panic.downcast_ref::<&str>().copied())
            .unwrap_or("panic");
        fail(RssnStatus::Panic, message)
    })
}

/// Borrows a C string argument as `&str`.
///
/// # Safety
/// `text` must be null or point to a NUL-terminated string that stays
/// valid for `'a`.
pub(crate) unsafe fn text<'a>(text: *const c_char) -> Result<&'a str, RssnStatus> {
    if text.is_null() {
        return Err(fail(RssnStatus::NullArgument, "null string argument"));
    }
    // SAFETY: non-null and NUL-terminated by the caller's contract.
    unsafe { CStr::from_ptr(text) }
        .to_str()
        .map_err(|_| fail(RssnStatus::InvalidUtf8, "string argument is not UTF-8"))
}

/// Hands a Rust string to C; null if it contains a NUL byte.
pub(crate) fn to_c(text: String) -> *mut c_char {
    CString::new(text).map_or(std::ptr::null_mut(), CString::into_raw)
}

/// The message of the last failed call on this thread (empty if none).
/// The pointer stays valid until the next failing rssn call on this
/// thread; do not free it.
#[unsafe(no_mangle)]
pub extern "C" fn rssn_last_error() -> *const c_char {
    LAST_ERROR.with(|e| e.borrow().as_ptr())
}

/// Releases a string returned by rssn. Null is ignored.
///
/// # Safety
/// `text` must be null or a string returned by rssn and not yet freed.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rssn_string_free(text: *mut c_char) {
    if !text.is_null() {
        // SAFETY: produced by `CString::into_raw` in `to_c`.
        drop(unsafe { CString::from_raw(text) });
    }
}

/// The crate version, e.g. `"0.3.0"`. Static; do not free.
#[unsafe(no_mangle)]
pub const extern "C" fn rssn_version() -> *const c_char {
    concat!(env!("CARGO_PKG_VERSION"), "\0").as_ptr().cast()
}

/// Runs the simulation scenario `name` (see
/// [`crate::sim::scenario::SCENARIOS`]) with JSON parameters and stores
/// the JSON result in `*out` (free with `rssn_string_free`).
///
/// # Safety
/// `name` and `params` must be NUL-terminated strings; `out` must be a
/// valid pointer.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rssn_sim_run(
    name: *const c_char,
    params: *const c_char,
    out: *mut *mut c_char,
) -> RssnStatus {
    guard(|| {
        if out.is_null() {
            return fail(RssnStatus::NullArgument, "null output pointer");
        }
        // SAFETY: forwarded caller contract.
        let (name, params) = match unsafe { (text(name), text(params)) } {
            | (Ok(n), Ok(p)) => (n, p),
            | (Err(e), _) | (_, Err(e)) => return e,
        };
        match crate::sim::scenario::run(name, params) {
            | Ok(json) => {
                // SAFETY: `out` is non-null and valid by contract.
                unsafe { *out = to_c(json) };
                RssnStatus::Ok
            },
            | Err(e) => fail(RssnStatus::Simulation, &e),
        }
    })
}

#[cfg(test)]
mod tests;
